-- This is a workaround for the missing DDL statements in migration V5.1.1.2

CREATE TABLE IF NOT EXISTS externaltooltype
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type            VARCHAR(255)                            NOT NULL,
    externalTool_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_externaltooltype PRIMARY KEY (id)
);

ALTER TABLE externaltooltype
    ADD CONSTRAINT fk_externaltooltype_externaltool_id FOREIGN KEY (externalTool_id) REFERENCES externaltool (id);

CREATE INDEX IF NOT EXISTS index_actionlogrecord_actiontype
    ON externaltooltype (id);

CREATE INDEX IF NOT EXISTS index_actionlogrecord_useridentifier
    ON externaltooltype (externaltool_id);

CREATE INDEX IF NOT EXISTS index_externaltooltype_externaltool_id
    ON externaltooltype (externaltool_id);
