#!/bin/sh
curl -X PUT "http://localhost:8080/api/dvs/root/groups/trees/roleAssignees/@chestnut?key=$ADMINKEY"
curl -X PUT "http://localhost:8080/api/dvs/root/groups/trees/roleAssignees/@spruce?key=$ADMINKEY"
