#!/bin/sh
. scripts/search/export-keys
echo "Creating bird and tree dataverses"
scripts/search/populate-bird-dvs1
scripts/search/create-bird-dvs1 > /tmp/bird-dvs1
scripts/search/populate-tree-dvs1
scripts/search/create-tree-dvs1 > /dev/null
echo "Creating some datasets"
curl -s --insecure --data-binary @scripts/search/tests/data/dataset-trees1.xml -H 'Content-Type: application/atom+xml' -u spruce:spruce https://localhost:8181/dvn/api/data-deposit/v1.1/swordv2/collection/dataverse/spruce | xmllint -format - >/dev/null
sed -i -e "s/123456/`uuidgen | cut -c-6`/" scripts/search/tests/data/dataset-finch1.json
# this is created on Mac by the sed command above
rm -f scripts/search/tests/data/dataset-finch1.json-e
curl -s -X POST -H "Content-type:application/json" -d @scripts/search/tests/data/dataset-finch1.json "http://localhost:8080/api/dvs/finches/datasets/?key=$FINCHKEY" >/dev/null
git checkout scripts/search/tests/data/dataset-finch1.json
echo "Uploading a file"
. scripts/search/assumptions
curl -s --insecure --data-binary @scripts/search/data/binary/trees.zip -H 'Content-Disposition: filename=trees.zip' -H 'Content-Type: application/zip' -H 'Packaging: http://purl.org/net/sword/package/SimpleZip' -u spruce:spruce https://localhost:8181/dvn/api/data-deposit/v1.1/swordv2/edit-media/study/$FIRST_SPRUCE_DOI >/dev/null
# give the file a little time to ingest
sleep 2
echo "Everything in draft, checking permissions. Silence is golden."
scripts/search/tests/query-unparseable
scripts/search/tests/permissions1
echo "Done."
. scripts/search/assumptions
echo "Giving $SPRUCE_USERNAME "admin" on Birds dataverse"
scripts/search/tests/grant-spruce-admin-on-birds
echo Re-testing permissions. Silence is golden
scripts/search/tests/permissions2
echo Done
. scripts/search/assumptions
echo "Revoking that role"
#curl -s -X DELETE "http://localhost:8080/api/dvs/$BIRDS_DATAVERSE/assignments/$SPRUCE_ADMIN_ON_BIRDS?key=$FINCHKEY" >/dev/null
scripts/search/tests/revoke-spruce-admin-on-birds
echo "Making sure original permissions are back. Silence is golden."
scripts/search/tests/permissions1
echo "Done"
