#!/bin/sh
. scripts/search/export-keys
OUTPUT=`curl -s -X POST -H "Content-type:application/json" -d "{\"assignee\": \"&shib/1\",\"role\": \"dvContributor\"}" "http://localhost:8080/api/dataverses/root/assignments?key=$ADMINKEY"`
echo $OUTPUT
echo $OUTPUT | jq .
#echo $OUTPUT | jq ' .data | {assignee,_roleAlias}'
