#!/bin/sh
. scripts/search/assumptions
curl -s -X POST -H 'Content-Type: application/x-www-form-urlencoded' "http://localhost:8080/api/roles/assignments?username=$SPRUCE_USERNAME&roleId=$ADMIN_ROLE&definitionPointId=$BIRDS_DATAVERSE&key=$FINCHKEY" | jq ' .data | {assignee,_roleAlias}'
