#!/bin/bash
# We assume you added a file called "trees.png" to the dataset at
# by running highlighting-setup03
#
# It doesn't have a description yet. Go make it "Trees are lovely."
# Handy link: http://localhost:8080/dataset.xhtml?id=17
#
# Then this test should pass.
#
# FIXME: It would be great if we could specify the descriptions of
# files in the zip file we upload to SWORD. See also
# https://redmine.hmdc.harvard.edu/issues/3232
#
diff <(curl -s 'http://localhost:8080/api/search?q=trees&showrelevance=true&key=nick') scripts/search/tests/expected/highlighting-nick-trees
diff <(curl -s 'http://localhost:8080/api/search?q=trees&showrelevance=true&key=pete') scripts/search/tests/expected/highlighting-pete-trees
