#!/bin/bash
# We assume you've added the bird and tree dataverses with highlighting-setup01
# We run the command below to create http://localhost:8080/dataset.xhtml?id=17
# in the "Trees" dataverse at http://localhost:8080/dataverse.xhtml?id=11
# with the following:
#
# Title: Rings of Trees and Other Observations
# Author: Tree, Tony
# Affiliation: Trees Inc.
# Contact E-mail: tony@trees.com
# Description: Trees have rings. Trees can be tall.
# Keyword: trees
# Keyword: rings
# Keyword: tall
# Subject: Medicine, Health & Life Sciences
# Notes: Many notes have been taken about trees over the years.
#
# Contributor:
#   Type: Data Collector
#   Name: Edward Trees Jr.
#
# FIXME dataset01-create-new.json is using hard-coded protocol and authority values from
# DatasetPage. Related ticket: https://github.com/IQSS/dataverse/issues/757
curl -s -X POST -H "Content-type:application/json" -d @scripts/search/data/dataset01-create-new.json http://localhost:8080/api/dvs/11/datasets/?key=$PETEKEY
