#!/bin/sh
. scripts/search/export-keys
OUTPUT=`curl -s -X POST -d @scripts/api/data/ipGroup-all.json http://localhost:8080/api/admin/groups/ip -H "Content-type:application/json"`
echo $OUTPUT
echo $OUTPUT | jq .
