#!/bin/bash
# After dropping your datbase and getting set up again per the dev guide,
# You should see no output from this script. Silence is golden.
# If you start creating dataverses and datasets, you should expect to see output.
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=nosuchuser') scripts/search/tests/expected/nosuchuser
diff <(curl -s 'http://localhost:8080/api/search?q=*') scripts/search/tests/expected/anon
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=__GUEST__') scripts/search/tests/expected/__GUEST__
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=pete') scripts/search/tests/expected/pete
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=uma') scripts/search/tests/expected/uma
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=gabbi') scripts/search/tests/expected/gabbi
# cathy should be able to see pete's stuff too
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=cathy') scripts/search/tests/expected/cathy
# nick should be able to see everything
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=nick') scripts/search/tests/expected/nick
