#!/bin/bash
#curl -s "http://localhost:8080/api/search?q=*" | python -m json.tool > scripts/search/tests/expected/anon3-full
diff <(curl -s "http://localhost:8080/api/search?q=*" | python -m json.tool) scripts/search/tests/expected/anon3-full
