#!/bin/bash
# We assume you've already run the main "permissions" script (no output)
# and then ran the "delete-dataverse" script, which will increment the
# database id's by one.
#
# Until you can create datasets via an API call, create these dataset as Pete in this order:
#
# dataset 1: title of "Pete's Unreleased Dataset" in "Pete's public place" but don't release it yet
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=nosuchuser') scripts/search/tests/expected/nosuchuser
diff <(curl -s 'http://localhost:8080/api/search?q=*') scripts/search/tests/expected/anon
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=__GUEST__') scripts/search/tests/expected/__GUEST__
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=pete') scripts/search/tests/expected/pete-datasets01
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=uma') scripts/search/tests/expected/uma
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=gabbi') scripts/search/tests/expected/gabbi
# cathy should be able to see pete's stuff too
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=cathy') scripts/search/tests/expected/cathy-datasets01
# nick should be able to see everything
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=nick') scripts/search/tests/expected/nick-datasets01
