#!/bin/bash
DIR=/tmp/keys
PETEKEY=`cat $DIR/pete`
UMAKEY=`cat $DIR/uma`
GABBIKEY=`cat $DIR/gabbi`
# After dropping your datbase and getting set up again per the dev guide,
# You should see no output from this script. Silence is golden.
# If you start creating dataverses and datasets, you should expect to see output.
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=nosuchuser' | jq .) scripts/search/tests/expected/nosuchuser
diff <(curl -s 'http://localhost:8080/api/search?q=*' | jq .) scripts/search/tests/expected/anon
diff <(curl -s "http://localhost:8080/api/search?q=*&key=$PETEKEY" | jq .) scripts/search/tests/expected/pete
diff <(curl -s "http://localhost:8080/api/search?q=*&key=$UMAKEY" | jq .) scripts/search/tests/expected/uma
diff <(curl -s "http://localhost:8080/api/search?q=*&key=$GABBIKEY" | jq .) scripts/search/tests/expected/gabbi
