#!/bin/bash
# We assume you've done everything in the permissions-datasets01 script.
#
# Next, you'll add a file "image.png" to the dataset you created.
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=nosuchuser') scripts/search/tests/expected/nosuchuser
diff <(curl -s 'http://localhost:8080/api/search?q=*') scripts/search/tests/expected/anon
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=__GUEST__') scripts/search/tests/expected/__GUEST__
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=pete') scripts/search/tests/expected/pete-datasets02
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=uma') scripts/search/tests/expected/uma
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=gabbi') scripts/search/tests/expected/gabbi
# cathy should be able to see pete's stuff too
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=cathy') scripts/search/tests/expected/cathy-datasets02
# nick should be able to see everything
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=nick') scripts/search/tests/expected/nick-datasets02
