#!/bin/bash
DIR=/tmp/searchusers
FINCHKEY=`cat $DIR/1 | jq .data.apiToken | tr -d \"`
SPRUCEKEY=`cat $DIR/4 | jq .data.apiToken | tr -d \"`
# After dropping your datbase and getting set up again per the dev guide,
# You should see no output from this script. Silence is golden.
# If you start creating dataverses and datasets, you should expect to see output.
diff <(curl -s 'http://localhost:8080/api/search?q=*&key=nosuchuser' | jq .) scripts/search/tests/expected/nosuchuser
diff <(curl -s 'http://localhost:8080/api/search?q=*' | jq .) scripts/search/tests/expected/anon

diff <(curl -s "http://localhost:8080/api/search/test?q=*&key=$FINCHKEY" | jq .data) scripts/search/tests/expected/finch1

diff <(curl -s "http://localhost:8080/api/search/test?q=*&key=$SPRUCEKEY" | jq .data) scripts/search/tests/expected/spruce1
