#!/bin/sh
. scripts/search/export-keys
OUTPUT=`cat /dev/null | curl -s --insecure -u $SPRUCEKEY: -X POST -H 'In-Progress: false' --data-binary @- https://localhost:8181/dvn/api/data-deposit/v1.1/swordv2/edit/dataverse/trees`
echo $OUTPUT
echo
echo $OUTPUT | xmllint -format -
