#!/bin/sh
OUTPUT=`cat /dev/null | curl -s --insecure -X POST -H 'In-Progress: false' --data-binary @- https://finch:finch@localhost:8181/dvn/api/data-deposit/v1.1/swordv2/edit/dataverse/finches`
echo $OUTPUT
echo
echo $OUTPUT | xmllint -format -
