package edu.harvard.iq.dataverse.authorization.providers.oauth2;

import edu.harvard.iq.dataverse.authorization.AuthenticatedUserDisplayInfo;
import edu.harvard.iq.dataverse.authorization.UserRecordIdentifier;

import java.io.Serializable;
import java.util.List;

/**
 * Describes a single user on a remote IDP that uses OAuth2.
 * Normally generated by {@link AbstractOAuth2Idp}.
 *
 * @author michael
 */
public class OAuth2UserRecord implements Serializable {

    /**
     * The expected value for the "idp" claim, identifying users authenticated by our
     * custom Builtin Users SPI.
     * <p>
     * This check is performed when the {@code API_BEARER_AUTH_USE_BUILTIN_USER_ON_ID_MATCH}
     * feature is enabled.
     * <p>
     * By verifying this value, we significantly reduce the risk of impersonation by
     * other IdPs, as they would have to be explicitly configured with this specific,
     * non-standard identifier.
     */
    public static final String BUILTIN_IDP_EXPECTED_CLAIM_VALUE = "dv-builtin-users-authenticator";

    /**
     * The following claim names are expected to be received when using the
     * CILogon org.cilogon.userinfo scope specification. For more details, see
     * https://www.cilogon.org/oidc
     */
    public static final String OIDC_USER_ID_CLAIM_NAME = "oidc";
    public static final String IDP_CLAIM_NAME = "idp";
    public static final String EMAIL_VERIFIED_CLAIM_NAME = "email_verified";

    private final String serviceId;

    /**
     * An immutable value, probably a number. Not a username that may change.
     */
    private final String idInService;

    /**
     * A potentially mutable String that is easier on the eye than a number.
     */
    private final String username;

    /**
     * For users originally coming from a Shibboleth IdP
     */
    private final String shibUniquePersistentIdentifier;

    /**
     * For brokered users coming from another OIDC provider
     */
    private final String oidcUserId;

    private final String idp;
    private final AuthenticatedUserDisplayInfo displayInfo;
    private final List<String> availableEmailAddresses;
    private final OAuth2TokenData tokenData;
    private final Boolean emailVerified;

    /**
     * Constructor for users without Shibboleth attributes.
     */
    public OAuth2UserRecord(
            String serviceId,
            String idInService,
            String username,
            OAuth2TokenData tokenData,
            AuthenticatedUserDisplayInfo displayInfo,
            List<String> availableEmailAddresses,
            Boolean emailVerified
            ) {
        this(serviceId, idInService, username, null, null, null, tokenData, displayInfo, availableEmailAddresses, emailVerified);
    }

    /**
     * Full constructor for OAuth2 user records.
     */
    public OAuth2UserRecord(
            String serviceId,
            String idInService,
            String username,
            String shibUniquePersistentIdentifier,
            String idp,
            String oidcUserId,
            OAuth2TokenData tokenData,
            AuthenticatedUserDisplayInfo displayInfo,
            List<String> availableEmailAddresses,
            Boolean emailVerified
    ) {
        this.serviceId = serviceId;
        this.idInService = idInService;
        this.username = username;
        this.shibUniquePersistentIdentifier = shibUniquePersistentIdentifier;
        this.idp = idp;
        this.oidcUserId = oidcUserId;
        this.tokenData = tokenData;
        this.displayInfo = displayInfo;
        this.availableEmailAddresses = availableEmailAddresses;
        this.emailVerified = emailVerified;
    }

    public String getServiceId() {
        return serviceId;
    }

    public String getIdInService() {
        return idInService;
    }

    public String getUsername() {
        return username;
    }

    public String getShibUniquePersistentIdentifier() {
        return shibUniquePersistentIdentifier;
    }

    public String getIdp() {
        return idp;
    }

    public String getOidcUserId() {
        return oidcUserId;
    }

    public List<String> getAvailableEmailAddresses() {
        return availableEmailAddresses;
    }

    public Boolean getEmailVerified() {
        return emailVerified;
    }

    public AuthenticatedUserDisplayInfo getDisplayInfo() {
        return displayInfo;
    }

    public OAuth2TokenData getTokenData() {
        return tokenData;
    }

    public UserRecordIdentifier getUserRecordIdentifier() {
        return new UserRecordIdentifier(serviceId, idInService);
    }

    public boolean hasShibAttributes() {
        return idp != null && shibUniquePersistentIdentifier != null;
    }

    public boolean hasOAuthAttributes() {
        return idp != null && oidcUserId != null;
    }

    public boolean hasBuiltinAttributes() {
        return idp != null && idp.equals(BUILTIN_IDP_EXPECTED_CLAIM_VALUE);
    }

    @Override
    public String toString() {
        return "OAuth2UserRecord{" +
                "serviceId='" + serviceId + '\'' +
                ", idInService='" + idInService + '\'' +
                '}';
    }
}
