#!/bin/sh
cd scripts/installer
export DB_NAME=dataverse_db
export DB_PORT=5432
export DB_HOST=localhost
export DB_USER=dataverse_app
export DB_PASS=secret
export RSERVE_HOST=localhost
export RSERVE_PORT=6311
export RSERVE_USER=rserve
export RSERVE_PASS=rserve
export SMTP_SERVER=localhost
export HOST_ADDRESS=`hostname`
export FILES_DIR=$HOME/dataverse/files
export MEM_HEAP_SIZE=2048
export GLASSFISH_DOMAIN=domain1
export GLASSFISH_ROOT=/Applications/NetBeans/glassfish4
cp pgdriver/postgresql-9.1-902.jdbc4.jar $GLASSFISH_ROOT/glassfish/lib
cp ../../conf/jhove/jhove.conf $GLASSFISH_ROOT/glassfish/domains/$GLASSFISH_DOMAIN/config/jhove.conf
./glassfish-setup.sh
