#!/bin/sh
scripts/database/homebrew/run-post-create-post-deploy
echo "Publishing root dataverse"
scripts/search/tests/publish-dataverse-root
echo "---"
echo "Creating search users"
scripts/search/populate-users > /dev/null
scripts/search/create-users > /dev/null
scripts/search/tests/grant-authusers-add-on-root
scripts/search/tests/create-all-and-test
#scripts/search/tests/create-saved-search-and-test
