#!/bin/sh
/Applications/NetBeans/glassfish4/glassfish/bin/asadmin stop-domain
scripts/database/homebrew/drop-database
scripts/search/clear
rm -rf ~/dataverse/files
scripts/database/homebrew/create-database
mvn clean
mvn package
/Applications/NetBeans/glassfish4/glassfish/bin/asadmin start-domain
# should probably use this instead: https://maven-glassfish-plugin.java.net/deploy-mojo.html
/Applications/NetBeans/glassfish4/glassfish/bin/asadmin deploy --force target/dataverse-4.0.war
#cp target/dataverse-4.0.war /Applications/NetBeans/glassfish4/glassfish/domains/domain1/autodeploy
sleep 15
scripts/database/homebrew/run-post-create-post-deploy
echo "---"
echo "Creating search users"
scripts/search/populate-users > /dev/null
scripts/search/create-users > /dev/null
. scripts/search/export-keys
echo "Creating bird and tree dataverses"
scripts/search/populate-bird-dvs1
scripts/search/create-bird-dvs1 > /dev/null
scripts/search/populate-tree-dvs1
scripts/search/create-tree-dvs1 > /dev/null
echo "Creating some datasets"
curl -s --insecure --data-binary @scripts/search/tests/data/dataset-trees1.xml -H 'Content-Type: application/atom+xml' -u spruce:spruce https://localhost:8181/dvn/api/data-deposit/v1/swordv2/collection/dataverse/spruce | xmllint -format - >/dev/null
sed -i -e "s/123456/`uuidgen | cut -c-6`/" scripts/search/tests/data/dataset-finch1.json
curl -s -X POST -H "Content-type:application/json" -d @scripts/search/tests/data/dataset-finch1.json http://localhost:8080/api/dvs/finches/datasets/?key=$FINCHKEY >/dev/null
git checkout scripts/search/tests/data/dataset-finch1.json
echo "Uploading a file"
. scripts/search/assumptions
curl -s --insecure --data-binary @scripts/search/data/binary/trees.zip -H 'Content-Disposition: filename=trees.zip' -H 'Content-Type: application/zip' -H 'Packaging: http://purl.org/net/sword/package/SimpleZip' -u spruce:spruce https://localhost:8181/dvn/api/data-deposit/v1.1/swordv2/edit-media/study/$FIRST_SPRUCE_DOI >/dev/null
# give the file a little time to ingest
sleep 2
echo "Everything in draft, checking permissions. Silence is golden."
scripts/search/tests/query-unparseable
scripts/search/tests/permissions1
echo "Done."
. scripts/search/assumptions
echo "Giving $SPRUCE_USERNAME "admin" on Birds dataverse"
curl -s -X POST -H 'Content-Type: application/x-www-form-urlencoded' "http://localhost:8080/api/roles/assignments?username=$SPRUCE_USERNAME&roleId=$ADMIN_ROLE&definitionPointId=$BIRDS_DATAVERSE&key=$FINCHKEY"
# FIXME: show the right permissions
#scripts/search/tests/permissions2
. scripts/search/assumptions
echo
echo "Revoking that role"
curl -s -X DELETE "http://localhost:8080/api/dvs/$BIRDS_DATAVERSE/assignments/$SPRUCE_ADMIN_ON_BIRDS?key=$FINCHKEY"
echo
echo "Making sure original permissions are back. Silence is golden."
scripts/search/tests/permissions1
echo "Done"
exit
# FIXME: clean up these old test and make them pass
scripts/search/tests/delete-dataverse
scripts/search/tests/highlighting-setup01 > /dev/null
scripts/search/tests/highlighting-setup02 > /dev/null
scripts/search/tests/highlighting-setup03 > /dev/null
scripts/search/tests/highlighting
scripts/search/tests/dataset-versioning01
scripts/search/tests/dataset-versioning02-setup > /dev/null
scripts/search/tests/dataset-versioning02
scripts/search/tests/dataset-versioning03-setup > /dev/null
scripts/search/tests/dataset-versioning03
# TODO: get the equivalent of these old scripts working again.
# They were taken out because we don't have a programmatic way
# to change descriptions for files ( https://redmine.hmdc.harvard.edu/issues/3232 ):
# 
# https://github.com/IQSS/dataverse/blob/e99f67cd82f18587e0b20eceef291b5f6df3d497/scripts/search/tests/permissions-datasets01
# https://github.com/IQSS/dataverse/blob/e99f67cd82f18587e0b20eceef291b5f6df3d497/scripts/search/tests/permissions-datasets02
# https://github.com/IQSS/dataverse/blob/e99f67cd82f18587e0b20eceef291b5f6df3d497/scripts/search/tests/dataset-versioning04
# https://github.com/IQSS/dataverse/blob/e99f67cd82f18587e0b20eceef291b5f6df3d497/scripts/search/tests/dataset-versioning05
# https://github.com/IQSS/dataverse/blob/e99f67cd82f18587e0b20eceef291b5f6df3d497/scripts/search/tests/dataset-versioning06
# https://github.com/IQSS/dataverse/blob/e99f67cd82f18587e0b20eceef291b5f6df3d497/scripts/search/tests/special-characters
