#!/bin/sh
scripts/database/homebrew/run-reference_data.sql
scripts/database/homebrew/run-non-dvnApp-role
cd scripts/api
./datasetfields.sh
./setup-users.sh
./setup-dvs.sh
cd ../..
curl -s http://localhost:8080/api/index
scripts/search/tests/permissions
