#!/bin/sh
# default "admin" password
# $2a$10$H8jca9BBbvCQAs2fU6TaseQeyD6ho3vZuIBKdlknDaR5lh69effde
~/.homebrew/bin/psql -c 'select username,encryptedpassword from builtinuser where id = 1' dataverse_db
~/.homebrew/bin/psql -c "update builtinuser set encryptedpassword='\$2a\$10\$H8jca9BBbvCQAs2fU6TaseQeyD6ho3vZuIBKdlknDaR5lh69effde' where id = 1" dataverse_db
