#!/bin/sh
OUT=$1
if [ "$1" = "apache" ] ; then
    PORT=:8181
elif [ "$1" = "glassfish" ] ; then
    PORT=""
else
    echo "Please specify either apache or glassfish".
    exit 1
fi
NUM=1
if [ "$2" -gt "$NUM" ] ; then
    echo foo
    NUM=$2
fi
for i in $(seq 1 $NUM); do
    locust -f basic_test_01.py -c 2 -r 2 -n 4 --no-web --print-stats --host=https://shibtest.dataverse.org$PORT 2>&1 | tee /tmp/$OUT.`date +%s`
done
