#!/bin/sh
/usr/local/glassfish4/glassfish/bin/asadmin undeploy dataverse-4.0
/usr/local/glassfish4/glassfish/bin/asadmin stop-domain
rm -rf /usr/local/glassfish4/glassfish/domains/domain1/files
psql -U dvnapp -c 'DROP DATABASE "dvndb"' template1
echo $?
curl http://localhost:8983/solr/update/json?commit=true -H "Content-type: application/json" -X POST -d "{\"delete\": { \"query\":\"*:*\"}}"
psql -U dvnapp -c 'CREATE DATABASE "dvndb" WITH OWNER = "dvnapp"' template1
echo $?
/usr/local/glassfish4/glassfish/bin/asadmin start-domain
/usr/local/glassfish4/glassfish/bin/asadmin deploy /tmp/dataverse-4.0.war
