#!/bin/sh
echo "deleting all data from Solr"
curl http://localhost:8983/solr/update/json?commit=true -H "Content-type: application/json" -X POST -d "{\"delete\": { \"query\":\"*:*\"}}"
# this was for elasticsearch
#curl -XDELETE http://localhost:9200/dataverse/
