#!/bin/bash
DIR=/tmp/searchusers
FINCHKEY=`cat $DIR/1 | jq .data.apiToken | tr -d \"`
echo "Database:"
scripts/search/dbperms $1 | grep '|'
echo "Solr:"
curl -s "http://localhost:8983/solr/collection1/select?rows=100&wt=json&indent=true&q=entityid%3A$1" | jq '.response.docs[] | {name_sort, perms_ss}'
echo "Java:"
curl -s "http://localhost:8080/api/search/perms?q=*&key=$FINCHKEY&id=$1" | jq '.data[]' 2>/dev/null
