#!/bin/sh
DVDIR='data/in/dataverses'
DSDIR='data/in/datasets'

for i in `ls $DVDIR`; do
  curl http://localhost:8080/api/dataverses -H 'Content-type:application/json' --data-binary @$DVDIR/$i
done

for i in `ls $DSDIR`; do
  curl http://localhost:8080/api/datasets -H 'Content-type:application/json' --data-binary @$DSDIR/$i
done
