#!/bin/sh
DIR='scripts/search/data/in/dv-psi'
USERDIR=/tmp/searchusers
PSIKEY=`cat $USERDIR/5 | jq .data.apiToken | tr -d \"`
curl -s -H "Content-type:application/json" -X POST -d @$DIR/1 "http://localhost:8080/api/dataverses/root?key=$PSIKEY"
echo

PARENT=psi
for i in {2..9}; do
  curl -s -H "Content-type:application/json" -X POST -d @$DIR/$i "http://localhost:8080/api/dataverses/$PARENT?key=$PSIKEY"
  echo
done

curl -s -H "Content-type:application/json" -X POST -d @$DIR/10 "http://localhost:8080/api/dataverses/psimali?key=$PSIKEY"
echo

curl -s -H "Content-type:application/json" -X POST -d @$DIR/11 "http://localhost:8080/api/dataverses/psimali?key=$PSIKEY"
echo
