#!/bin/bash -x
~/.homebrew/bin/psql -c "select * from savedsearch;" dataverse_db
~/.homebrew/bin/psql -c "select * from savedsearchfilterquery;" dataverse_db
exit
~/.homebrew/bin/psql -c "drop table savedsearch cascade;" dataverse_db
~/.homebrew/bin/psql -c "drop table savedsearchfilterquery cascade;" dataverse_db

