#!/bin/bash
# `source path/to/this/file` so you can use these keys elsewhere
export ADMINKEY=`cat /tmp/setup-all.sh.out | grep apiToken| jq .data.apiToken | tr -d \"`
export SEARCH_USER_DIR=/tmp/searchusers
export FINCHKEY=`cat $SEARCH_USER_DIR/1 | jq .data.apiToken | tr -d \"`
export SPARROWKEY=`cat $SEARCH_USER_DIR/2 | jq .data.apiToken | tr -d \"`
export WRENKEY=`cat $SEARCH_USER_DIR/3 | jq .data.apiToken | tr -d \"`
export SPRUCEKEY=`cat $SEARCH_USER_DIR/4 | jq .data.apiToken | tr -d \"`
export CHESTNUTKEY=`cat $SEARCH_USER_DIR/5 | jq .data.apiToken | tr -d \"`
export PSIADMINKEY=`cat $SEARCH_USER_DIR/6 | jq .data.apiToken | tr -d \"`
