#!/bin/bash
BASEDIR='scripts/search'
OUTDIR='data/in/dv-psi'
FULL_OUTDIR="$BASEDIR/$OUTDIR"
rm -rf $FULL_OUTDIR
mkdir -p $FULL_OUTDIR
cd $BASEDIR
count=1; ./tab2json-dvs data/dv-psi.tsv | while read i; do echo $i | python -m json.tool > $OUTDIR/$count; let count++; done
