#!/bin/sh
curl -s 'http://localhost:8983/solr/collection1/select?rows=1000000&wt=json&indent=true&q=*%3A*'
# show combination of public stuff OR pete's private stuff
# curl -s --globoff 'http://localhost:8983/solr/collection1/select?rows=100&wt=json&indent=true&q=*&fq=({!join+from=groups_s+to=perms_ss}id:group_public+OR+{!join+from=groups_s+to=perms_ss}id:group_user2)' | jq '.response.docs[] | {name_sort}'
# https://github.com/IQSS/dataverse/issues/1262
# curl 'http://localhost:8983/solr/collection1/select?rows=1000000&wt=json&indent=true&hl=true&hl.fl=*&q=wright&hl.snippets=10'
# remember elasticsearch? :)
#curl 'http://localhost:9200/_search?pretty=true&q=*'
