#!/bin/bash
curl -X PUT -d true http://localhost:8080/api/admin/settings/:SearchApiNonPublicAllowed
echo
curl -s http://localhost:8080/api/admin/savedsearches -X POST -H 'Content-type:application/json' --upload-file scripts/search/data/savedSearchMaliBasicHealth.json | jq .
