#!/usr/bin/env python
import sys
from optparse import OptionParser
import csv
try:
    import json
except ImportError:
    import simplejson as json

parser = OptionParser()
options, args = parser.parse_args()

if args:
    csv_file = open(args[0])
else:
    csv_file = sys.stdin

reader = csv.DictReader(csv_file, delimiter="\t")
rows = [row for row in reader]
for row in rows:
    if "name" in row and "alias" in  row and row["id"] == "1":
        # root dataverse can't have an owner
        del row["owner"]
        pass
    else:
        owner_id = row["owner"]
        row["owner"] = {"id": owner_id}
    print json.dumps(row)
csv_file.close()
# sample dataverse file:
#id	name	alias	owner	contactEmail	description	affiliation
#2	Birds	birds	1	birds@birds.com	A birds dataverse	Birds Inc.
# sample dataset file:
#id	title	author	owner	description	citationDate	distributor
#1	birdstudy1	Dr. Finch	1	About birds	2013-12-11	For the Birds
