# This file contains the strings for dataset types that can be
# translated into other languages (French, Spanish, etc.).
# Only the default dataset type (dataset) is included, as an example.
# If you add additional dataset types (e.g. software), you don't
# need to add them to this file if you are only running in English.
# However, if you are running in additional languages, you should
# add the additional dataset types to this file.
dataset.displayName=Dataset