metadatablock.name=repositorycharacteristics
metadatablock.displayName=Repository Characteristics
metadatablock.displayFacet=
datasetfieldtype.repositoryOrHosting.title=Repository or Hosting
datasetfieldtype.securityAndTechnicalSafeguards.title=Security and Technical Safeguards
datasetfieldtype.sustainabilityAndLongevity.title=Sustainability and Longevity
datasetfieldtype.standardsCertification.title=Standards Certification
datasetfieldtype.repositoryOrHosting.description=Where and how the data are stored (e.g. institutional repository, cloud) and the oversight and management policies that ensure ethical and transparent handling of the data
datasetfieldtype.securityAndTechnicalSafeguards.description=The mechanisms that the repository or hosting platform uses to prevent tampering with or unauthorized access to the data
datasetfieldtype.sustainabilityAndLongevity.description=The strategies that the repository or hosting platform uses to support the long-term preservation and maintenance of the data
datasetfieldtype.standardsCertification.description=The certification of the repository or hosting platform (e.g. CoreTrustSeal)
datasetfieldtype.repositoryOrHosting.watermark=
datasetfieldtype.securityAndTechnicalSafeguards.watermark=
datasetfieldtype.sustainabilityAndLongevity.watermark=
datasetfieldtype.standardsCertification.watermark=