metadatablock.name=review
metadatablock.displayName=Review Metadata
metadatablock.displayFacet=Review
datasetfieldtype.itemReviewed.title=Item Reviewed
datasetfieldtype.itemReviewedUrl.title=URL
datasetfieldtype.itemReviewedType.title=Type
datasetfieldtype.itemReviewedCitation.title=Citation
datasetfieldtype.itemReviewed.description=The item being reviewed
datasetfieldtype.itemReviewedUrl.description=The URL of the item being reviewed
datasetfieldtype.itemReviewedType.description=The type of the item being reviewed
datasetfieldtype.itemReviewedCitation.description=The full bibliographic citation of the item being reviewed
datasetfieldtype.itemReviewed.watermark=
datasetfieldtype.itemReviewedUrl.watermark=
datasetfieldtype.itemReviewedType.watermark=
datasetfieldtype.itemReviewedCitation.watermark=
controlledvocabulary.itemReviewedType.audiovisual=Audiovisual
controlledvocabulary.itemReviewedType.award=Award
controlledvocabulary.itemReviewedType.book=Book
controlledvocabulary.itemReviewedType.book_chapter=Book Chapter
controlledvocabulary.itemReviewedType.collection=Collection
controlledvocabulary.itemReviewedType.computational_notebook=Computational Notebook
controlledvocabulary.itemReviewedType.conference_paper=Conference Paper
controlledvocabulary.itemReviewedType.conference_proceeding=Conference Proceeding
controlledvocabulary.itemReviewedType.datapaper=DataPaper
controlledvocabulary.itemReviewedType.dataset=Dataset
controlledvocabulary.itemReviewedType.dissertation=Dissertation
controlledvocabulary.itemReviewedType.event=Event
controlledvocabulary.itemReviewedType.image=Image
controlledvocabulary.itemReviewedType.interactive_resource=Interactive Resource
controlledvocabulary.itemReviewedType.instrument=Instrument
controlledvocabulary.itemReviewedType.journal=Journal
controlledvocabulary.itemReviewedType.journal_article=Journal Article
controlledvocabulary.itemReviewedType.model=Model
controlledvocabulary.itemReviewedType.output_management_plan=Output Management Plan
controlledvocabulary.itemReviewedType.peer_review=Peer Review
controlledvocabulary.itemReviewedType.physical_object=Physical Object
controlledvocabulary.itemReviewedType.preprint=Preprint
controlledvocabulary.itemReviewedType.project=Project
controlledvocabulary.itemReviewedType.report=Report
controlledvocabulary.itemReviewedType.service=Service
controlledvocabulary.itemReviewedType.software=Software
controlledvocabulary.itemReviewedType.sound=Sound
controlledvocabulary.itemReviewedType.standard=Standard
controlledvocabulary.itemReviewedType.study_registration=Study Registration
controlledvocabulary.itemReviewedType.text=Text
controlledvocabulary.itemReviewedType.workflow=Workflow
controlledvocabulary.itemReviewedType.other=Other
