metadatablock.name=trusteddatadimensionsintensities
metadatablock.displayName=Trusted Data Dimensions and Intensities
metadatablock.displayFacet=
datasetfieldtype.authorAndProvenance.title=Author and Provenance
datasetfieldtype.integrityAndUsability.title=Integrity and Usability
datasetfieldtype.fitnessForScopeAndContextualRelevance.title=Fitness for Scope and Contextual Relevance
datasetfieldtype.licensingAndLegalClarity.title=Licensing and Legal Clarity
datasetfieldtype.transparencyOfMethodsAndDocumentation.title=Transparency of Methods and Documentation
datasetfieldtype.biasEquityAndRepresentativeness.title=Bias, Equity, and Representativeness
datasetfieldtype.reviewTarget.description=The type of research object reviewed
datasetfieldtype.authorAndProvenance.description=The level of trust in the data creators and in other provenance information
datasetfieldtype.integrityAndUsability.description=The level of trust in the accuracy, completeness, and ease of use of the data
datasetfieldtype.fitnessForScopeAndContextualRelevance.description=The level of trust in the suitability of the data for specific contexts, questions, or policy applications
datasetfieldtype.licensingAndLegalClarity.description=The level of trust in the explicitness of the data’s usage rights and their compliance with relevant laws and regulations
datasetfieldtype.transparencyOfMethodsAndDocumentation.description=The level of trust in the clarity of the descriptions of data collection and processing methods
datasetfieldtype.biasEquityAndRepresentativeness.description=The level of trust in the inclusivity and fairness of the coverage of the data
datasetfieldtype.reviewTarget.watermark=
datasetfieldtype.authorAndProvenance.watermark=
datasetfieldtype.integrityAndUsability.watermark=
datasetfieldtype.fitnessForScopeAndContextualRelevance.watermark=
datasetfieldtype.licensingAndLegalClarity.watermark=
datasetfieldtype.transparencyOfMethodsAndDocumentation.watermark=
datasetfieldtype.biasEquityAndRepresentativeness.watermark=
controlledvocabulary.authorAndProvenance.low=Low
controlledvocabulary.authorAndProvenance.medium=Medium
controlledvocabulary.authorAndProvenance.high=High
controlledvocabulary.integrityAndUsability.low=Low
controlledvocabulary.integrityAndUsability.medium=Medium
controlledvocabulary.integrityAndUsability.high=High
controlledvocabulary.fitnessForScopeAndContextualRelevance.low=Low
controlledvocabulary.fitnessForScopeAndContextualRelevance.medium=Medium
controlledvocabulary.fitnessForScopeAndContextualRelevance.high=High
controlledvocabulary.licensingAndLegalClarity.low=Low
controlledvocabulary.licensingAndLegalClarity.medium=Medium
controlledvocabulary.licensingAndLegalClarity.high=High
controlledvocabulary.transparencyOfMethodsAndDocumentation.low=Low
controlledvocabulary.transparencyOfMethodsAndDocumentation.medium=Medium
controlledvocabulary.transparencyOfMethodsAndDocumentation.high=High
controlledvocabulary.biasEquityAndRepresentativeness.low=Low
controlledvocabulary.biasEquityAndRepresentativeness.medium=Medium
controlledvocabulary.biasEquityAndRepresentativeness.high=High