version: "3.9"

services:

  keycloak:
    image: 'quay.io/keycloak/keycloak:21.0'
    command:
      - "start-dev"
      - "--import-realm"
    environment:
      - KEYCLOAK_ADMIN=kcadmin
      - KEYCLOAK_ADMIN_PASSWORD=kcpassword
      - KEYCLOAK_LOGLEVEL=DEBUG
    ports:
      - "8090:8080"
    volumes:
      - './test-realm.json:/opt/keycloak/data/import/test-realm.json'
