# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.define "cdh", autostart: false do |cdh|
    config.vm.hostname = "solr"
    solr.vm.box = "puppet-vagrant-boxes.puppetlabs.com-centos-65-x64-virtualbox-puppet.box"
    config.vm.synced_folder ".", "/dataverse"
    config.vm.network "private_network", type: "dhcp"
    config.vm.network "forwarded_port", guest: 8983, host: 9001
  end

  config.vm.define "dataverse", primary: true do |dataverse|
    dataverse.vm.hostname = "dataverse"
    dataverse.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box"
    dataverse.vm.box = "puppet-vagrant-boxes.puppetlabs.com-centos-65-x64-virtualbox-puppet.box"

    mailserver = "localhost"
    if ENV['MAIL_SERVER'].nil?
      puts "MAIL_SERVER environment variable not specified. Using #{mailserver} by default.\nTo specify it in bash: export MAIL_SERVER=localhost"
    else
      mailserver = ENV['MAIL_SERVER']
      puts "MAIL_SERVER environment variable found, using #{mailserver}"
    end

    dataverse.vm.provision "shell", path: "../setup.sh"
    dataverse.vm.provision "shell", path: "scripts/vagrant/install-dataverse.sh", args: mailserver

    config.vm.network "private_network", type: "192.168.39.100"
    config.vm.network "forwarded_port", guest: 80, host: 10080
    config.vm.network "forwarded_port", guest: 443, host: 10443
    config.vm.network "forwarded_port", guest: 8080, host: 18080
    config.vm.network "forwarded_port", guest: 8181, host: 18181

    # FIXME: use /dataverse/downloads instead
    config.vm.synced_folder "../../../downloads", "/downloads"
    # FIXME: use /dataverse/conf instead
    config.vm.synced_folder "../../../conf", "/conf"
    # FIXME: use /dataverse/scripts instead
    config.vm.synced_folder "../../../scripts", "/scripts"
    config.vm.synced_folder "../../../", "/dataverse"
  end

end
