insert into customfieldmap
 ( id, sourcetemplate, sourcedatasetfield, targetdatasetfield )
values

(99,'GSD Studio Template','StudentName','gsdStudentName'),
(2,'GSD Studio Template','StudentsProgramofStudy','gsdStudentProgram'),
(3,'GSD Studio Template','CourseName','gsdCourseName'),
(4,'GSD Studio Template','FacultyName','gsdFacultyName'),
(5,'GSD Studio Template','CoreStudioCoordinator','gsdCoordinator'),
(6,'GSD Studio Template','SemesterYear','gsdSemester'),
(7,'GSD Studio Template','FacultyRecommendation','gsdRecommendation'),
(8,'GSD Studio Template','CountryNation','country'),
(9,'GSD Studio Template','StateProvince','state'),
(10,'GSD Studio Template','City','city'),
(11,'GSD Studio Template','SiteType','gsdSiteType'),
(12,'GSD Studio Template','ProgramBrief','gsdProgramBrief'),
(13,'GSD Studio Template','TypesofRepresentationMediumFormat','gsdTypes'),
(14,'GSD Studio Template','Tags','gsdTags'),
(15,'GSD Studio Template','DataUploadedBy','depositor'),
(16,'GSD Studio Template','Notes','notesText'),
(17,'GSD 2013 2014','StudentName','gsdStudentName'),
(18,'GSD 2013 2014','StudentsProgramofStudy','gsdStudentProgram'),
(19,'GSD 2013 2014','CourseName','gsdCourseName'),
(20,'GSD 2013 2014','FacultyName','gsdFacultyName'),
(21,'GSD 2013 2014','CoreStudioCoordinator','gsdCoordinator'),
(22,'GSD 2013 2014','SemesterYear','gsdSemester'),
(23,'GSD 2013 2014','FacultyRecommendation','gsdRecommendation'),
(24,'GSD 2013 2014','CountryNation','country'),
(25,'GSD 2013 2014','StateProvince','state'),
(26,'GSD 2013 2014','City','city'),
(27,'GSD 2013 2014','SiteType','gsdSiteType'),
(28,'GSD 2013 2014','ProgramBrief','gsdProgramBrief'),
(29,'GSD 2013 2014','TypesofRepresentationMediumFormat','gsdTypes'),
(30,'GSD 2013 2014','Tags','gsdTags'),
(31,'GSD 2013 2014','DataUploadedBy','depositor'),
(32,'GSD 2013 2014','Notes','notesText'),
(33, 'GSD 20134 2014','Accreditation','gsdAccreditation'),
(34, 'GSD Studio Template','Accreditation','gsdAccreditation');
