#!/bin/sh
echo "Calling testscripts/install..."
export HOST_ADDRESS=localhost
export GLASSFISH_ROOT=/opt/payara6
export FILES_DIR=/opt/payara6/glassfish/domains/domain1/files
export DB_NAME=dvndb
export DB_PORT=5432
export DB_HOST=localhost
export DB_USER=dvnapp
export DB_PASS=secret
export RSERVE_HOST=localhost
export RSERVE_PORT=6311
export RSERVE_USER=rserve
export RSERVE_PASS=rserve
export SMTP_SERVER=localhost
export MEM_HEAP_SIZE=2048
export GLASSFISH_DOMAIN=domain1
cd scripts/installer
#cp ../../conf/jhove/jhove.conf $GLASSFISH_ROOT/glassfish/domains/$GLASSFISH_DOMAIN/config/jhove.conf
cp /opt/dv/testdata/jhove.conf $GLASSFISH_ROOT/glassfish/domains/$GLASSFISH_DOMAIN/config/jhove.conf
cp /opt/dv/testdata/jhoveConfig.xsd $GLASSFISH_ROOT/glassfish/domains/$GLASSFISH_DOMAIN/config/jhoveConfig.xsd
./as-setup.sh dvndb
