#!/bin/sh
if [ -z "$1" ]; then
    echo "No custom build number specified. Using branch name and commit id."
    SCRIPT=$(readlink -f "$0")
    SCRIPTPATH=$(dirname "$SCRIPT")
    $SCRIPTPATH/custom-build-number-hook
else
    echo "build.number=$@" > src/main/java/BuildNumber.properties
fi
