#!/bin/sh
if [ -z "$1" ]; then
    echo "No custom build number specified. Using branch name and commit id."
    SCRIPTPATH=$(dirname "$0")
    cd $(git rev-parse --show-toplevel)
    $SCRIPTPATH/custom-build-number-hook
else
    echo "build.number=$@" > src/main/java/BuildNumber.properties
fi
