# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

unless defined? STATIC_IP_CDH 
  STATIC_IP_CDH = "192.168.39.14"
end

unless defined? STATIC_IP_DATAVERSE 
  STATIC_IP_DATAVERSE = "192.168.39.20"
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.define "cloudera-quickstart" do |cdh|
    cdh.vm.hostname = "quickstart.cloudera"
    cdh.vm.box = "UNCC-DSI/cloudera-quickstart"
    cdh.vm.box_version = "~> 5.4.0"
    cdh.vm.network "private_network", ip: STATIC_IP_CDH
    cdh.vm.graceful_halt_timeout = 180
  end

  config.vm.define "dataverse", primary: true do |dataverse|
    dataverse.vm.hostname = "dataverse"
    dataverse.vm.box = "puppetlabs/centos-6.6-64-puppet"
    dataverse.vm.network "private_network", ip: STATIC_IP_DATAVERSE

    unless defined? mailserver
      mailserver = "localhost"
      if ENV['MAIL_SERVER'].nil?
        puts "MAIL_SERVER environment variable not specified. Using #{mailserver} by default.\nTo specify it in bash: export MAIL_SERVER=localhost"
      else
        mailserver = ENV['MAIL_SERVER']
        puts "MAIL_SERVER environment variable found, using #{mailserver}"
      end
    end

    dataverse.vm.provision "dataversePrereqs", type: "shell", path: "../setup.sh"
    dataverse.vm.provision "killFirewall", type: "shell", inline: "service iptables stop"
    dataverse.vm.provision "dataverseSetup", type: "shell", 
      path: "../install-dataverse.sh",
      args: "-c dvcollection -h #{STATIC_IP_DATAVERSE} -m #{mailserver} -s #{STATIC_IP_CDH}"

    dataverse.vm.synced_folder "../../../", "/dataverse"
  end

end
