package edu.harvard.iq.dataverse.authorization.oauth2;

import edu.harvard.iq.dataverse.authorization.AuthenticatedUserDisplayInfo;

/**
 * Describes a single user on a remote IDP that uses OAuth2.
 * Normally generated by {@link AbstractOAuth2Idp}.
 * 
 * @author michael
 */
public class OAuth2UserRecord {
    
    private final String serviceId;
    
    /** Probably the username. */
    private final String idInService;
    
    private final String accessToken;
    
    private final AuthenticatedUserDisplayInfo displayInfo;

    public OAuth2UserRecord(String aServiceId, String anIdInService, String anAccessToken,  AuthenticatedUserDisplayInfo aDisplayInfo) {
        serviceId = aServiceId;
        idInService = anIdInService;
        accessToken = anAccessToken;
        displayInfo = aDisplayInfo;
    }

    public String getServiceId() {
        return serviceId;
    }

    public String getIdInService() {
        return idInService;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public AuthenticatedUserDisplayInfo getDisplayInfo() {
        return displayInfo;
    }

    @Override
    public String toString() {
        return "OAuth2UserRecord{" + "serviceId=" + serviceId + ", idInService=" + idInService + '}';
    }
    
}
