#!/bin/sh
# relies on experimental feature, see https://github.com/IQSS/dataverse/issues/1299
# curl -X PUT -d true http://localhost:8080/api/s/settings/:SearchApiNonPublicAllowed
curl "http://localhost:8080/api/search?key=$SPARROWKEY&show_relevance=true&q=sparrow"
