# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# these are dummy values, obviously
export UPLOADHOST=dcmsrv
export DVAPIKEY=burrito
export DVHOSTINT=dvsrv
export DVHOST=dvsrv
