# initial docker-compose file for combined Dataverse and DCM with shared filesystem

version: '3'

services:
  dcmsrv:
    build:
      context: .
      dockerfile: dcmsrv.dockerfile
    container_name: dcmsrv
    volumes:
      - hold:/hold
  rsalsrv:
    build:
      context: .
      dockerfile: rsalsrv.dockerfile
    container_name: rsalsrv
#    image: rsalrepo_rsal
    volumes:
      - hold:/hold
      - ./:/mnt
    environment:
      DV_HOST: http://dvsrv:8080
      DV_APIKEY: burrito
    ports:
      - "8889:80"
      - "873:873"
  dvsrv:
    build:
      context: .
      dockerfile: dv0dcm.dockerfile
    container_name: dvsrv
    volumes:
      - hold:/hold
      - ./:/mnt
    ports:
      - "8083:8080"
      - "8084:80"
  client:
    build:
      context: .
      dockerfile: c6client.dockerfile
    command: sleep infinity
    container_name: dcm_client
    volumes:
      - ./:/mnt

volumes:
  hold:

