#!/bin/bash
USERNAME=admin
PASSWORD=$USERNAME
if [ -z "$1" ]; then
  HOSTNAME=localhost:8181
else
  HOSTNAME=$1
fi
URL=https://$HOSTNAME/dvn/api/data-deposit/v1/swordv2/service-document
echo Retrieving service document from $URL >&2
curl -s --insecure -u $USERNAME:$PASSWORD $URL \
| xmllint -format -
