#!/bin/bash
. scripts/search/export-keys
if [ -z "$1" ]; then
  HOSTNAME=localhost:8181
else
  HOSTNAME=$1
fi
URL=https://$HOSTNAME/dvn/api/data-deposit/v1/swordv2/service-document
echo Retrieving service document from $URL >&2
OUTPUT=`curl -s --insecure -u $ADMINKEY: $URL`
echo $OUTPUT
echo $OUTPUT | xmllint -format -
