#!/bin/sh
USERNAME=pete
PASSWORD=pete
DVN_SERVER=localhost:8181
GLOBAL_ID=myIdentifier
curl --insecure -s https://$USERNAME:$PASSWORD@$DVN_SERVER/dvn/api/data-deposit/v1/swordv2/statement/study/$GLOBAL_ID \
| xmllint -format - \
#| xpath '//entry/title'
