#!/bin/sh
USERNAME=pete
PASSWORD=pete
DVN_SERVER=localhost:8181
#GLOBAL_ID=hdl:TEST/12345
GLOBAL_ID=`scripts/api/data-deposit/list-datasets | xpath '//id/text()' | cut -d'/' -f11,12`
curl --insecure -s https://$USERNAME:$PASSWORD@$DVN_SERVER/dvn/api/data-deposit/v1/swordv2/edit/study/$GLOBAL_ID \
| xmllint -format -
