# Glassfish and Dataverse in one Docker image, as suggested by danmcp.
# 
# TODO: Start with the Dataverse 4.2.3 version at https://github.com/pdurbin/ndslabs-dataverse/blob/v4.2.3.1/dockerfiles/dataverse/Dockerfile
#
# TODO: Once we get Dataverse 4.2.3 working, we can try Dataverse 4.7 from https://github.com/pdurbin/ndslabs-dataverse/blob/upgrade-4.7/dockerfiles/dataverse/Dockerfile
