CREATE TABLE IF NOT EXISTS DatasetType
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_datasettype PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DatasetType_licenses
(
    DatasetType_id BIGINT NOT NULL,
    licenses_id    BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS DatasetType_metadataBlocks
(
    DatasetType_id    BIGINT NOT NULL,
    metadataBlocks_id BIGINT NOT NULL
);

ALTER TABLE DatasetType
    ADD CONSTRAINT uc_828171b214f7369ee92a28781 UNIQUE (name);

ALTER TABLE DatasetType_licenses
    ADD CONSTRAINT fk_datlic_on_dataset_type FOREIGN KEY (DatasetType_id) REFERENCES DatasetType (id);

ALTER TABLE DatasetType_licenses
    ADD CONSTRAINT fk_datlic_on_license FOREIGN KEY (licenses_id) REFERENCES License (id);

ALTER TABLE DatasetType_metadataBlocks
    ADD CONSTRAINT fk_datmet_on_dataset_type FOREIGN KEY (DatasetType_id) REFERENCES DatasetType (id);

ALTER TABLE DatasetType_metadataBlocks
    ADD CONSTRAINT fk_datmet_on_metadata_block FOREIGN KEY (metadataBlocks_id) REFERENCES MetadataBlock (id);