CREATE TABLE IF NOT EXISTS MakeDataCountProcessState
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    yearMonth            VARCHAR(255)                            NOT NULL,
    state                INTEGER                                 NOT NULL,
    stateChangeTimestamp TIMESTAMP WITHOUT TIME ZONE,
    server               VARCHAR(255),
    CONSTRAINT pk_makedatacountprocessstate PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_18d578c22760ad21e31cc873d ON MakeDataCountProcessState (yearMonth);