ALTER TABLE DATASETFIELDTYPE ADD COLUMN frenchdescription VARCHAR(1000);
ALTER TABLE DATASETFIELDTYPE ADD COLUMN frenchtitle VARCHAR(255);
ALTER TABLE METADATABLOCK ADD COLUMN frenchdisplayname VARCHAR(255);
ALTER TABLE CONTROLLEDVOCABULARYVALUE ADD COLUMN frenchstrvalue VARCHAR(255);