#!/bin/sh
export HOST_ADDRESS=phoenix.dataverse.org
export GLASSFISH_ROOT=/usr/local/glassfish4
export FILES_DIR=/usr/local/glassfish4/glassfish/domains/domain1/files
export DB_NAME=dvndb
export DB_PORT=5432
export DB_HOST=localhost
export DB_USER=dvnapp
export DB_PASS=secret
export RSERVE_HOST=localhost
export RSERVE_PORT=6311
export RSERVE_USER=rserve
export RSERVE_PASS=rserve
export SMTP_SERVER=localhost
export MEM_HEAP_SIZE=2048
export GLASSFISH_DOMAIN=domain1
cd scripts/installer
cp pgdriver/postgresql-8.4-703.jdbc4.jar $GLASSFISH_ROOT/glassfish/lib
cp ../../conf/jhove/jhove.conf $GLASSFISH_ROOT/glassfish/domains/$GLASSFISH_DOMAIN/config/jhove.conf
./glassfish-setup.sh
