#!/bin/sh
WAR=$(ls -1 /tmp/dataverse-*.war | head -1 | cut -d/ -f3)
VERSION=$(echo $WAR | sed 's/.war//g')
/usr/local/glassfish4/glassfish/bin/asadmin list-applications
/usr/local/glassfish4/glassfish/bin/asadmin undeploy $VERSION
/usr/local/glassfish4/glassfish/bin/asadmin stop-domain
rm -rf /usr/local/glassfish4/glassfish/domains/domain1/files
#psql -U postgres -c "CREATE ROLE dvnapp UNENCRYPTED PASSWORD 'secret' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN" template1
psql -U dvnapp -c 'DROP DATABASE "dvndb"' template1
echo $?
curl http://localhost:8983/solr/update/json?commit=true -H "Content-type: application/json" -X POST -d "{\"delete\": { \"query\":\"*:*\"}}"
psql -U dvnapp -c 'CREATE DATABASE "dvndb" WITH OWNER = "dvnapp"' template1
echo $?
/usr/local/glassfish4/glassfish/bin/asadmin start-domain
/usr/local/glassfish4/glassfish/bin/asadmin deploy /tmp/$WAR
