-- Astrophysics metadatablock definitions.
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (117, 'Type', 'Type', 'type', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (118, 'Facility', 'Facility', 'facility', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (119, 'Instrument', 'Instrument', 'instrument', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (120, 'RedshiftType', 'RedshiftType', 'redshiftType', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (121, 'Coverage', 'Coverage', 'coverage', TRUE, TRUE, TRUE, TRUE, 1 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (122, 'Coverage.Polarization', 'Coverage.Polarization', 'coverage.Polarization', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (123, 'Coverage.Redshift.MinimumValue', 'Coverage.Redshift.MinimumValue', 'coverage.Redshift.MinimumValue', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (124, 'Coverage.Redshift.MaximumValue', 'Coverage.Redshift.MaximumValue', 'coverage.Redshift.MaximumValue', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (125, 'Coverage.Spatial', 'Coverage.Spatial', 'coverage.Spatial', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (126, 'Coverage.Spectral', 'Coverage.Spectral', 'coverage.Spectral', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (127, 'Coverage.Spectral.Bandpass', 'Coverage.Spectral.Bandpass', 'coverage.Spectral.Bandpass', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (128, 'Coverage.Spectral.CentralWavelength', 'Coverage.Spectral.CentralWavelength', 'coverage.Spectral.CentralWavelength', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (129, 'Coverage.MinimumWavelength', 'Coverage.MinimumWavelength', 'coverage.MinimumWavelength', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (130, 'Coverage.MaximumWavelength', 'Coverage.MaximumWavelength', 'coverage.MaximumWavelength', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (131, 'Coverage.Temporal.StartTime', 'Coverage.Temporal.StartTime', 'coverage.Temporal.StartTime', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (132, 'Coverage.Temporal.StopTime', 'Coverage.Temporal.StopTime', 'coverage.Temporal.StopTime', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (133, 'Coverage.Depth', 'Coverage.Depth', 'coverage.Depth', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (134, 'Coverage.ObjectDensity', 'Coverage.ObjectDensity', 'coverage.ObjectDensity', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (135, 'Coverage.ObjectCount', 'Coverage.ObjectCount', 'coverage.ObjectCount', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (136, 'Coverage.SkyFraction', 'Coverage.SkyFraction', 'coverage.SkyFraction', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (137, 'Resolution', 'Resolution', 'resolution', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (138, 'Resolution.Redshift', 'Resolution.Redshift', 'resolution.Redshift', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (139, 'Resolution.Spatial', 'Resolution.Spatial', 'resolution.Spatial', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (140, 'Resolution.Spectral', 'Resolution.Spectral', 'resolution.Spectral', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (141, 'Resolution.Temporal', 'Resolution.Temporal', 'resolution.Temporal', TRUE, TRUE, TRUE, TRUE, 6 );
INSERT INTO datasetfield (id,title,description, name,basicSearchField,advancedSearchField, searchResultField,  allowControlledVocabulary, metadatablock_id) VALUES (142, 'UCD (Unified Content Descriptors)', 'UCD (Unified Content Descriptors)', 'ucd', TRUE, TRUE, TRUE, TRUE, 6 );
-- field type definitions: 
-- (everything is a textBox, except for Coverage.Temporal.StartTime
-- and Coverage.Temporal.StopTime, which are dates)
UPDATE datasetfield SET fieldtype = 'textBox' where id = 117;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 118;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 119;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 120;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 121;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 122;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 123;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 124;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 125;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 126;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 127;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 128;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 129;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 130;
UPDATE datasetfield SET fieldtype = 'date' WHERE id = 131;
UPDATE datasetfield SET fieldtype = 'date' WHERE id = 132;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 133;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 134;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 135;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 136;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 137;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 138;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 139;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 140;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 141;
UPDATE datasetfield SET fieldtype = 'textBox' where id = 142;
-- parent field definitions: 
-- "Coverage" nested fields: 
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 122;
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 123;
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 124;
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 125;
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 126;
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 127;
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 128;
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 129;
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 130;
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 131;
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 132;
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 133;
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 134;
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 135;
UPDATE datasetfield SET parentdatasetfield_id = 121 where id = 136;
-- "Resolution" nested fields: 
UPDATE datasetfield SET parentdatasetfield_id = 137 where id = 138;
UPDATE datasetfield SET parentdatasetfield_id = 137 where id = 139;
UPDATE datasetfield SET parentdatasetfield_id = 137 where id = 140;
UPDATE datasetfield SET parentdatasetfield_id = 137 where id = 141;
-- display orders: "type" is 0, everything else is 1, for now:
UPDATE datasetfield SET displayorder = 0 WHERE id=117;
UPDATE datasetfield SET displayorder = 1 WHERE id=118;
UPDATE datasetfield SET displayorder = 1 WHERE id=119;
UPDATE datasetfield SET displayorder = 1 WHERE id=120;
UPDATE datasetfield SET displayorder = 1 WHERE id=121;
UPDATE datasetfield SET displayorder = 1 WHERE id=122;
UPDATE datasetfield SET displayorder = 1 WHERE id=123;
UPDATE datasetfield SET displayorder = 1 WHERE id=124;
UPDATE datasetfield SET displayorder = 1 WHERE id=125;
UPDATE datasetfield SET displayorder = 1 WHERE id=126;
UPDATE datasetfield SET displayorder = 1 WHERE id=127;
UPDATE datasetfield SET displayorder = 1 WHERE id=128;
UPDATE datasetfield SET displayorder = 1 WHERE id=129;
UPDATE datasetfield SET displayorder = 1 WHERE id=130;
UPDATE datasetfield SET displayorder = 1 WHERE id=131;
UPDATE datasetfield SET displayorder = 1 WHERE id=132;
UPDATE datasetfield SET displayorder = 1 WHERE id=133;
UPDATE datasetfield SET displayorder = 1 WHERE id=134;
UPDATE datasetfield SET displayorder = 1 WHERE id=135;
UPDATE datasetfield SET displayorder = 1 WHERE id=136;
UPDATE datasetfield SET displayorder = 1 WHERE id=137;
UPDATE datasetfield SET displayorder = 1 WHERE id=138;
UPDATE datasetfield SET displayorder = 1 WHERE id=139;
UPDATE datasetfield SET displayorder = 1 WHERE id=140;
UPDATE datasetfield SET displayorder = 1 WHERE id=141;
UPDATE datasetfield SET displayorder = 1 WHERE id=142;
-- finally, add the astro metadatablock to the root dataverse:
INSERT INTO dvobject_metadatablock(dataverse_id, metadatablocks_id) VALUES (1, 6);