pipeline {
  agent any

  stages {

    stage('Build') {
      steps {
	// clean plate
        sh 'rm -rf target/'
	// package warfile
	sh 'mvn -DcompilerArgument=-Xlint:unchecked test -P all-unit-tests package'
	// generate HTML SureFire report
	sh 'mvn surefire-report:report'
      }
    }

    stage('Test') {
      steps {
        script {
          // if pull request originates from IQSS, CHANGE_FORK is undefined
          if (env.CHANGE_FORK) {
            env.EC2_REPO = env.CHANGE_FORK
          } else {
            env.EC2_REPO = env.GIT_URL
          }
        }
	sh '/usr/bin/curl -O https://raw.githubusercontent.com/IQSS/dataverse-ansible/master/ec2/ec2-create-instance.sh'
	sh '/usr/bin/bash ./ec2-create-instance.sh -b ${CHANGE_BRANCH} -r ${EC2_REPO} -t jenkins_delete_me -l target -g tests/jenkins/groupvars.yml'
      }
    }

    stage('Post') {
      steps {
	junit 'target/surefire-reports/*.xml'
      }
    }
  }
}
