-- Ordered list of ROR identifiers associated with an authenticated user.
-- The ROR with the lowest displayorder is the user's primary ROR.
CREATE TABLE IF NOT EXISTS authenticateduserror (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    authenticateduser_id BIGINT NOT NULL,
    rorid VARCHAR(255) NOT NULL,
    displayorder INTEGER NOT NULL,
    CONSTRAINT fk_authenticateduserror_authenticateduser FOREIGN KEY (authenticateduser_id) REFERENCES authenticateduser(id) ON DELETE CASCADE,
    CONSTRAINT authenticateduserror_displayorder_nonnegative CHECK (displayorder >= 0),
    -- Deferred so that reordering or replacing a user's RORs within one transaction
    -- doesn't trip the constraints while rows are updated one at a time.
    CONSTRAINT authenticateduserror_user_ror_unique UNIQUE (authenticateduser_id, rorid) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT authenticateduserror_user_order_unique UNIQUE (authenticateduser_id, displayorder) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS index_authenticateduserror_authenticateduser_id ON authenticateduserror (authenticateduser_id);
CREATE INDEX IF NOT EXISTS index_authenticateduserror_rorid ON authenticateduserror (rorid);
