CREATE INDEX IF NOT EXISTS INDEX_GUESTBOOKRESPONSE_responsetime ON GUESTBOOKRESPONSE (responsetime);
CREATE INDEX IF NOT EXISTS INDEX_GUESTBOOKRESPONSE_dataset_not_access_req ON GUESTBOOKRESPONSE (dataset_id) WHERE eventtype != 'AccessRequest';
CREATE INDEX IF NOT EXISTS INDEX_GUESTBOOKRESPONSE_datafile_not_access_req ON GUESTBOOKRESPONSE (datafile_id) WHERE eventtype != 'AccessRequest';
