ALTER TABLE DATAVERSEFEATUREDITEM ADD COLUMN IF NOT EXISTS type VARCHAR(45) default 'custom';
ALTER TABLE DATAVERSEFEATUREDITEM ADD COLUMN IF NOT EXISTS dvobject_id bigint;
ALTER TABLE DATAVERSEFEATUREDITEM ALTER COLUMN content DROP NOT NULL;
