-- Create the curationstatus table if it doesn't exist
CREATE TABLE IF NOT EXISTS curationstatus (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(255),
    datasetversion_id BIGINT NOT NULL,
    authenticateduser_id BIGINT NULL,
    createtime TIMESTAMP,
    CONSTRAINT fk_curationstatus_datasetversion FOREIGN KEY (datasetversion_id) REFERENCES datasetversion(id),
    CONSTRAINT fk_curationstatus_authenticateduser FOREIGN KEY (authenticateduser_id) REFERENCES authenticateduser(id)
);

CREATE INDEX IF NOT EXISTS index_curationstatus_datasetversion ON curationstatus (datasetversion_id);

-- Migrate existing data from datasetversion.externalstatuslabel to curationstatus if it hasn't been done already
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'datasetversion' AND column_name = 'externalstatuslabel') THEN
        INSERT INTO curationstatus (label, datasetversion_id, authenticateduser_id, createtime)
        SELECT DISTINCT ON (externalstatuslabel, id) externalstatuslabel, id, NULL, NULL
        FROM datasetversion
        WHERE externalstatuslabel IS NOT NULL AND externalstatuslabel != ''
        AND NOT EXISTS (
            SELECT 1 FROM curationstatus
            WHERE curationstatus.label = datasetversion.externalstatuslabel
            AND curationstatus.datasetversion_id = datasetversion.id
        );

        -- Drop the externalstatuslabel column from datasetversion
        ALTER TABLE datasetversion DROP COLUMN IF EXISTS externalstatuslabel;
    END IF;
END
$$;
