ALTER TABLE controlledvocabularyvalue 
ADD COLUMN displaygroup text;

update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 2  where strvalue = 'Abkhaz';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 3 where strvalue = 'Afar';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 4 where strvalue = 'Afrikaans';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 5 where strvalue = 'Akan';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 6 where strvalue = 'Albanian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 7 where strvalue = 'Amharic';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 8 where strvalue = 'Arabic';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 9 where strvalue = 'Aragonese';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 10 where strvalue = 'Armenian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 11 where strvalue = 'Assamese';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 12 where strvalue = 'Avaric';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 13 where strvalue = 'Avestan';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 14 where strvalue = 'Aymara';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 15 where strvalue = 'Azerbaijani';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 16 where strvalue = 'Bambara';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 17 where strvalue = 'Bashkir';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 18 where strvalue = 'Basque';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 19 where strvalue = 'Belarusian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 20 where strvalue = 'Bengali, Bangla';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 21 where strvalue = 'Bihari';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 22 where strvalue = 'Bislama';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 23 where strvalue = 'Bosnian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 24 where strvalue = 'Breton';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 25 where strvalue = 'Bulgarian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 26 where strvalue = 'Burmese';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 27 where strvalue = 'Catalan,Valencian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 28 where strvalue = 'Chamorro';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 29 where strvalue = 'Chechen';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 30 where strvalue = 'Chichewa, Chewa, Nyanja';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 31 where strvalue = 'Chinese';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 32 where strvalue = 'Chuvash';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 33 where strvalue = 'Cornish';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 34 where strvalue = 'Corsican';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 35 where strvalue = 'Cree';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 36 where strvalue = 'Croatian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 37 where strvalue = 'Czech';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 38 where strvalue = 'Danish';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 39 where strvalue = 'Divehi, Dhivehi, Maldivian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 40 where strvalue = 'Dutch';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 41 where strvalue = 'Dzongkha';
update controlledvocabularyvalue set displaygroup = 'popular', displayorder = 1 where strvalue = 'English';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 42 where strvalue = 'Esperanto';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 43 where strvalue = 'Estonian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 44 where strvalue = 'Ewe';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 45 where strvalue = 'Faroese';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 46 where strvalue = 'Fijian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 47 where strvalue = 'Finnish';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 48 where strvalue = 'French';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 49 where strvalue = 'Fula, Fulah, Pulaar, Pular';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 50 where strvalue = 'Galician';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 51 where strvalue = 'Georgian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 52 where strvalue = 'German';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 53 where strvalue = 'Greek (modern)';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 54 where strvalue = 'Guaraní';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 55 where strvalue = 'Gujarati';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 56 where strvalue = 'Haitian, Haitian Creole';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 57 where strvalue = 'Hausa';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 58 where strvalue = 'Hebrew (modern)';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 59 where strvalue = 'Herero';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 60 where strvalue = 'Hindi';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 61 where strvalue = 'Hiri Motu';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 62 where strvalue = 'Hungarian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 63 where strvalue = 'Interlingua';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 64 where strvalue = 'Indonesian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 65 where strvalue = 'Interlingue';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 66 where strvalue = 'Irish';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 67 where strvalue = 'Igbo';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 68 where strvalue = 'Inupiaq';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 69 where strvalue = 'Ido';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 70 where strvalue = 'Icelandic';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 71 where strvalue = 'Italian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 72 where strvalue = 'Inuktitut';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 73 where strvalue = 'Japanese';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 74 where strvalue = 'Javanese';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 75 where strvalue = 'Kalaallisut, Greenlandic';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 76 where strvalue = 'Kannada';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 77 where strvalue = 'Kanuri';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 78 where strvalue = 'Kashmiri';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 79 where strvalue = 'Kazakh';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 80 where strvalue = 'Khmer';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 81 where strvalue = 'Kikuyu, Gikuyu';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 82 where strvalue = 'Kinyarwanda';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 83 where strvalue = 'Kyrgyz';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 84 where strvalue = 'Komi';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 85 where strvalue = 'Kongo';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 86 where strvalue = 'Korean';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 87 where strvalue = 'Kurdish';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 88 where strvalue = 'Kwanyama, Kuanyama';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 89 where strvalue = 'Latin';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 90 where strvalue = 'Luxembourgish, Letzeburgesch';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 91 where strvalue = 'Ganda';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 92 where strvalue = 'Limburgish, Limburgan, Limburger';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 93 where strvalue = 'Lingala';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 94 where strvalue = 'Lao';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 95 where strvalue = 'Lithuanian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 96 where strvalue = 'Luba-Katanga';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 97 where strvalue = 'Latvian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 98 where strvalue = 'Manx';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 99 where strvalue = 'Macedonian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 100 where strvalue = 'Malagasy';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 101 where strvalue = 'Malay';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 102 where strvalue = 'Malayalam';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 103 where strvalue = 'Maltese';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 104 where strvalue = 'Māori';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 105 where strvalue = 'Marathi (Marāṭhī)';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 106 where strvalue = 'Marshallese';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 107 where strvalue = 'Mixtepec Mixtec';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 108 where strvalue = 'Mongolian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 109 where strvalue = 'Nauru';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 110 where strvalue = 'Navajo, Navaho';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 111 where strvalue = 'Northern Ndebele';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 112 where strvalue = 'Nepali';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 113 where strvalue = 'Ndonga';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 114 where strvalue = 'Norwegian Bokmål';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 115 where strvalue = 'Norwegian Nynorsk';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 116 where strvalue = 'Norwegian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 117 where strvalue = 'Nuosu';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 118 where strvalue = 'Southern Ndebele';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 119 where strvalue = 'Occitan';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 120 where strvalue = 'Ojibwe, Ojibwa';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 121 where strvalue = 'Old Church Slavonic,Church Slavonic,Old Bulgarian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 122 where strvalue = 'Oromo';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 123 where strvalue = 'Oriya';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 124 where strvalue = 'Ossetian, Ossetic';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 125 where strvalue = 'Panjabi, Punjabi';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 126 where strvalue = 'Pāli';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 127 where strvalue = 'Persian (Farsi)';
update controlledvocabularyvalue set displaygroup = 'popular', displayorder = 0 where strvalue = 'Polish';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 128 where strvalue = 'Pashto, Pushto';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 129 where strvalue = 'Portuguese';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 130 where strvalue = 'Quechua';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 131 where strvalue = 'Romansh';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 132 where strvalue = 'Kirundi';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 133 where strvalue = 'Romanian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 134 where strvalue = 'Russian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 135 where strvalue = 'Sanskrit (Saṁskṛta)';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 136 where strvalue = 'Sardinian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 137 where strvalue = 'Sindhi';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 138 where strvalue = 'Northern Sami';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 139 where strvalue = 'Samoan';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 140 where strvalue = 'Sango';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 141 where strvalue = 'Serbian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 142 where strvalue = 'Scottish Gaelic, Gaelic';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 143 where strvalue = 'Shona';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 144 where strvalue = 'Sinhala, Sinhalese';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 145 where strvalue = 'Slovak';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 146 where strvalue = 'Slovene';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 147 where strvalue = 'Somali';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 148 where strvalue = 'Southern Sotho';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 149 where strvalue = 'Spanish, Castilian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 150 where strvalue = 'Sundanese';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 151 where strvalue = 'Swahili';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 152 where strvalue = 'Swati';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 153 where strvalue = 'Swedish';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 154 where strvalue = 'Tamil';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 155 where strvalue = 'Telugu';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 156 where strvalue = 'Tajik';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 157 where strvalue = 'Thai';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 158 where strvalue = 'Tigrinya';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 159 where strvalue = 'Tibetan Standard, Tibetan, Central';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 160 where strvalue = 'Turkmen';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 161 where strvalue = 'Tagalog';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 162 where strvalue = 'Tswana';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 163 where strvalue = 'Tonga (Tonga Islands)';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 164 where strvalue = 'Turkish';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 165 where strvalue = 'Tsonga';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 166 where strvalue = 'Tatar';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 167 where strvalue = 'Twi';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 168 where strvalue = 'Tahitian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 169 where strvalue = 'Uyghur, Uighur';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 170 where strvalue = 'Ukrainian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 171 where strvalue = 'Urdu';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 172 where strvalue = 'Uzbek';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 173 where strvalue = 'Venda';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 174 where strvalue = 'Vietnamese';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 175 where strvalue = 'Volapük';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 176 where strvalue = 'Walloon';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 177 where strvalue = 'Welsh';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 178 where strvalue = 'Wolof';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 179 where strvalue = 'Western Frisian';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 180 where strvalue = 'Xhosa';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 181 where strvalue = 'Yiddish';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 182 where strvalue = 'Yoruba';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 183 where strvalue = 'Zhuang, Chuang';
update controlledvocabularyvalue set displaygroup = 'not_popular', displayorder = 184 where strvalue = 'Zulu';
update controlledvocabularyvalue set displaygroup = 'not_applicable_group', displayorder = 185 where strvalue = 'Not applicable';

UPDATE datasetfieldtype
SET inputrendereroptions = '{"sortByLocalisedStringsOrder" : "true"}'
WHERE name = 'subject';
