ALTER TABLE controlledvocabularyvalue 
ADD COLUMN displaygroup text;

DELETE FROM controlledvocabularyvalue
WHERE datasetfieldtype_id = 35;

INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (55, 2, '', 'Abkhaz', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (56, 3, '', 'Afar', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (57, 4, '', 'Afrikaans', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (58, 5, '', 'Akan', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (59, 6, '', 'Albanian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (60, 7, '', 'Amharic', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (61, 8, '', 'Arabic', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (62, 9, '', 'Aragonese', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (63, 10, '', 'Armenian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (64, 11, '', 'Assamese', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (65, 12, '', 'Avaric', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (66, 13, '', 'Avestan', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (67, 14, '', 'Aymara', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (68, 15, '', 'Azerbaijani', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (69, 16, '', 'Bambara', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (70, 17, '', 'Bashkir', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (71, 18, '', 'Basque', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (72, 19, '', 'Belarusian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (73, 20, '', 'Bengali, Bangla', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (74, 21, '', 'Bihari', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (75, 22, '', 'Bislama', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (76, 23, '', 'Bosnian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (77, 24, '', 'Breton', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (78, 25, '', 'Bulgarian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (79, 26, '', 'Burmese', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (80, 27, '', 'Catalan,Valencian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (81, 28, '', 'Chamorro', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (82, 29, '', 'Chechen', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (83, 30, '', 'Chichewa, Chewa, Nyanja', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (84, 31, '', 'Chinese', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (85, 32, '', 'Chuvash', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (86, 33, '', 'Cornish', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (87, 34, '', 'Corsican', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (88, 35, '', 'Cree', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (89, 36, '', 'Croatian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (90, 37, '', 'Czech', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (91, 38, '', 'Danish', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (92, 39, '', 'Divehi, Dhivehi, Maldivian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (93, 40, '', 'Dutch', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (94, 41, '', 'Dzongkha', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (95, 1, '', 'English', 35, 'popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (96, 42, '', 'Esperanto', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (97, 43, '', 'Estonian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (98, 44, '', 'Ewe', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (99, 45, '', 'Faroese', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (100, 46, '', 'Fijian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (101, 47, '', 'Finnish', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (102, 48, '', 'French', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (103, 49, '', 'Fula, Fulah, Pulaar, Pular', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (104, 50, '', 'Galician', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (105, 51, '', 'Georgian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (106, 52, '', 'German', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (107, 53, '', 'Greek (modern)', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (108, 54, '', 'Guaraní', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (109, 55, '', 'Gujarati', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (110, 56, '', 'Haitian, Haitian Creole', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (111, 57, '', 'Hausa', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (112, 58, '', 'Hebrew (modern)', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (113, 59, '', 'Herero', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (114, 60, '', 'Hindi', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (115, 61, '', 'Hiri Motu', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (116, 62, '', 'Hungarian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (117, 63, '', 'Interlingua', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (118, 64, '', 'Indonesian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (119, 65, '', 'Interlingue', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (120, 66, '', 'Irish', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (121, 67, '', 'Igbo', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (122, 68, '', 'Inupiaq', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (123, 69, '', 'Ido', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (124, 70, '', 'Icelandic', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (125, 71, '', 'Italian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (126, 72, '', 'Inuktitut', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (127, 73, '', 'Japanese', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (128, 74, '', 'Javanese', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (129, 75, '', 'Kalaallisut, Greenlandic', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (130, 76, '', 'Kannada', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (131, 77, '', 'Kanuri', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (132, 78, '', 'Kashmiri', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (133, 79, '', 'Kazakh', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (134, 80, '', 'Khmer', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (135, 81, '', 'Kikuyu, Gikuyu', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (136, 82, '', 'Kinyarwanda', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (137, 83, '', 'Kyrgyz', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (138, 84, '', 'Komi', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (139, 85, '', 'Kongo', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (140, 86, '', 'Korean', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (141, 87, '', 'Kurdish', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (142, 88, '', 'Kwanyama, Kuanyama', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (143, 89, '', 'Latin', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (144, 90, '', 'Luxembourgish, Letzeburgesch', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (145, 91, '', 'Ganda', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (146, 92, '', 'Limburgish, Limburgan, Limburger', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (147, 93, '', 'Lingala', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (148, 94, '', 'Lao', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (149, 95, '', 'Lithuanian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (150, 96, '', 'Luba-Katanga', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (151, 97, '', 'Latvian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (152, 98, '', 'Manx', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (153, 99, '', 'Macedonian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (154, 100, '', 'Malagasy', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (155, 101, '', 'Malay', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (156, 102, '', 'Malayalam', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (157, 103, '', 'Maltese', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (158, 104, '', 'Māori', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (159, 105, '', 'Marathi (Marāṭhī)', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (160, 106, '', 'Marshallese', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (161, 107, '', 'Mixtepec Mixtec', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (162, 108, '', 'Mongolian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (163, 109, '', 'Nauru', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (164, 110, '', 'Navajo, Navaho', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (165, 111, '', 'Northern Ndebele', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (166, 112, '', 'Nepali', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (167, 113, '', 'Ndonga', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (168, 114, '', 'Norwegian Bokmål', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (169, 115, '', 'Norwegian Nynorsk', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (170, 116, '', 'Norwegian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (171, 117, '', 'Nuosu', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (172, 118, '', 'Southern Ndebele', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (173, 119, '', 'Occitan', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (174, 120, '', 'Ojibwe, Ojibwa', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (175, 121, '', 'Old Church Slavonic,Church Slavonic,Old Bulgarian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (176, 122, '', 'Oromo', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (177, 123, '', 'Oriya', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (178, 124, '', 'Ossetian, Ossetic', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (179, 125, '', 'Panjabi, Punjabi', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (180, 126, '', 'Pāli', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (181, 127, '', 'Persian (Farsi)', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (182, 0, '', 'Polish', 35, 'popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (183, 128, '', 'Pashto, Pushto', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (184, 129, '', 'Portuguese', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (185, 130, '', 'Quechua', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (186, 131, '', 'Romansh', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (187, 132, '', 'Kirundi', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (188, 133, '', 'Romanian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (189, 134, '', 'Russian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (190, 135, '', 'Sanskrit (Saṁskṛta)', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (191, 136, '', 'Sardinian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (192, 137, '', 'Sindhi', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (193, 138, '', 'Northern Sami', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (194, 139, '', 'Samoan', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (195, 140, '', 'Sango', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (196, 141, '', 'Serbian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (197, 142, '', 'Scottish Gaelic, Gaelic', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (198, 143, '', 'Shona', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (199, 144, '', 'Sinhala, Sinhalese', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (200, 145, '', 'Slovak', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (201, 146, '', 'Slovene', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (202, 147, '', 'Somali', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (203, 148, '', 'Southern Sotho', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (204, 149, '', 'Spanish, Castilian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (205, 150, '', 'Sundanese', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (206, 151, '', 'Swahili', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (207, 152, '', 'Swati', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (208, 153, '', 'Swedish', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (209, 154, '', 'Tamil', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (210, 155, '', 'Telugu', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (211, 156, '', 'Tajik', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (212, 157, '', 'Thai', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (213, 158, '', 'Tigrinya', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (214, 159, '', 'Tibetan Standard, Tibetan, Central', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (215, 160, '', 'Turkmen', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (216, 161, '', 'Tagalog', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (217, 162, '', 'Tswana', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (218, 163, '', 'Tonga (Tonga Islands)', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (219, 164, '', 'Turkish', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (220, 165, '', 'Tsonga', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (221, 166, '', 'Tatar', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (222, 167, '', 'Twi', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (223, 168, '', 'Tahitian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (224, 169, '', 'Uyghur, Uighur', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (225, 170, '', 'Ukrainian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (226, 171, '', 'Urdu', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (227, 172, '', 'Uzbek', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (228, 173, '', 'Venda', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (229, 174, '', 'Vietnamese', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (230, 175, '', 'Volapük', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (231, 176, '', 'Walloon', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (232, 177, '', 'Welsh', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (233, 178, '', 'Wolof', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (234, 179, '', 'Western Frisian', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (235, 180, '', 'Xhosa', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (236, 181, '', 'Yiddish', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (237, 182, '', 'Yoruba', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (238, 183, '', 'Zhuang, Chuang', 35, 'not_popular');
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (239, 184, '', 'Zulu', 35, 'not_popular');
<<<<<<< HEAD
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (240, 185, '', 'Not applicable', 35, 'not_applicable_group');
=======
INSERT INTO controlledvocabularyvalue (id, displayorder, identifier, strvalue, datasetfieldtype_id, displaygroup) VALUES (240, 185, '', 'Not applicable', 35, 'not_applicable');
>>>>>>> b0ef00cc7e866e71d8987780310cc42d60f9da88

UPDATE datasetfieldtype
SET inputrendereroptions = '{"sortByLocalisedStringsOrder" : "true"}'
WHERE name = 'subject';
