UPDATE datasetfieldtype dsf SET displayorder = displayorder + 3 WHERE dsf.displayorder > 2;

INSERT INTO datasetfieldtype (advancedsearchfieldtype, allowcontrolledvocabulary, allowmultiples, description,
                              displayformat, displayoncreate, displayorder, facetable, fieldtype, name, required, title,
                              uri, validationformat, watermark, metadatablock_id, parentdatasetfieldtype_id,
                              inputrenderertype, inputrendereroptions)
VALUES (false, false, true, 'Dataset title translated into another language', '',
        true, 3, false, 'NONE', 'titleTranslation', false, 'Title Translation', '',
        NULL, '', 1, NULL, 'TEXT', '{}');


INSERT INTO datasetfieldtype (advancedsearchfieldtype, allowcontrolledvocabulary, allowmultiples, description,
                              displayformat, displayoncreate, displayorder, facetable, fieldtype, name, required, title,
                              uri, validationformat, watermark, metadatablock_id, parentdatasetfieldtype_id,
                              inputrenderertype, inputrendereroptions)
(SELECT true, false, false, 'Text of the title translation', '',
        true, 4, false, 'TEXT', 'titleTranslationText', false, 'Text', '',
        NULL, '', 1, id, 'TEXT', '{}' FROM datasetfieldtype where name='titleTranslation');

INSERT INTO datasetfieldtype (advancedsearchfieldtype, allowcontrolledvocabulary, allowmultiples, description,
                              displayformat, displayoncreate, displayorder, facetable, fieldtype, name, required, title,
                              uri, validationformat, watermark, metadatablock_id, parentdatasetfieldtype_id,
                              inputrenderertype, inputrendereroptions)
 (SELECT true, true, false, 'Language of the title translation', '(#VALUE)',
        true, 5, false, 'TEXT', 'titleTranslationLanguage', false, 'Language', '',
        NULL, '', 1, id, 'VOCABULARY_SELECT', '{"sortByLocalisedStringsOrder" : "true"}' FROM datasetfieldtype where name='titleTranslation');

INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Polish', 0, dsft.id, 'popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'English', 1, dsft.id, 'popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Abkhaz', 2, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Afar', 3, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Afrikaans', 4, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Akan', 5, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Albanian', 6, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Amharic', 7, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Arabic', 8, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Aragonese', 9, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Armenian', 10, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Assamese', 11, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Avaric', 12, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Avestan', 13, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Aymara', 14, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Azerbaijani', 15, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Bambara', 16, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Bashkir', 17, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Basque', 18, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Belarusian', 19, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Bengali, Bangla', 20, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Bihari', 21, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Bislama', 22, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Bosnian', 23, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Breton', 24, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Bulgarian', 25, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Burmese', 26, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Catalan,Valencian', 27, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Chamorro', 28, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Chechen', 29, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Chichewa, Chewa, Nyanja', 30, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Chinese', 31, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Chuvash', 32, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Cornish', 33, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Corsican', 34, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Cree', 35, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Croatian', 36, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Czech', 37, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Danish', 38, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Divehi, Dhivehi, Maldivian', 39, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Dutch', 40, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Dzongkha', 41, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Esperanto', 42, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Estonian', 43, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Ewe', 44, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Faroese', 45, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Fijian', 46, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Finnish', 47, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'French', 48, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Fula, Fulah, Pulaar, Pular', 49, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Galician', 50, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Georgian', 51, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'German', 52, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Greek (modern)', 53, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Guaraní', 54, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Gujarati', 55, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Haitian, Haitian Creole', 56, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Hausa', 57, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Hebrew (modern)', 58, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Herero', 59, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Hindi', 60, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Hiri Motu', 61, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Hungarian', 62, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Interlingua', 63, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Indonesian', 64, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Interlingue', 65, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Irish', 66, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Igbo', 67, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Inupiaq', 68, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Ido', 69, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Icelandic', 70, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Italian', 71, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Inuktitut', 72, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Japanese', 73, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Javanese', 74, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Kalaallisut, Greenlandic', 75, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Kannada', 76, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Kanuri', 77, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Kashmiri', 78, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Kazakh', 79, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Khmer', 80, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Kikuyu, Gikuyu', 81, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Kinyarwanda', 82, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Kyrgyz', 83, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Komi', 84, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Kongo', 85, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Korean', 86, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Kurdish', 87, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Kwanyama, Kuanyama', 88, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Latin', 89, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Luxembourgish, Letzeburgesch', 90, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Ganda', 91, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Limburgish, Limburgan, Limburger', 92, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Lingala', 93, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Lao', 94, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Lithuanian', 95, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Luba-Katanga', 96, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Latvian', 97, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Manx', 98, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Macedonian', 99, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Malagasy', 100, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Malay', 101, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Malayalam', 102, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Maltese', 103, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Māori', 104, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Marathi (Marāṭhī)', 105, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Marshallese', 106, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Mixtepec Mixtec', 107, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Mongolian', 108, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Nauru', 109, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Navajo, Navaho', 110, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Northern Ndebele', 111, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Nepali', 112, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Ndonga', 113, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Norwegian Bokmål', 114, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Norwegian Nynorsk', 115, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Norwegian', 116, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Nuosu', 117, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Southern Ndebele', 118, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Occitan', 119, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Ojibwe, Ojibwa', 120, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Old Church Slavonic,Church Slavonic,Old Bulgarian', 121, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Oromo', 122, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Oriya', 123, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Ossetian, Ossetic', 124, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Panjabi, Punjabi', 125, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Pāli', 126, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Persian (Farsi)', 127, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Pashto, Pushto', 128, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Portuguese', 129, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Quechua', 130, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Romansh', 131, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Kirundi', 132, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Romanian', 133, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Russian', 134, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Sanskrit (Saṁskṛta)', 135, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Sardinian', 136, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Sindhi', 137, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Northern Sami', 138, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Samoan', 139, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Sango', 140, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Serbian', 141, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Scottish Gaelic, Gaelic', 142, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Shona', 143, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Sinhala, Sinhalese', 144, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Slovak', 145, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Slovene', 146, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Somali', 147, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Southern Sotho', 148, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Spanish, Castilian', 149, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Sundanese', 150, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Swahili', 151, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Swati', 152, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Swedish', 153, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Tamil', 154, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Telugu', 155, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Tajik', 156, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Thai', 157, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Tigrinya', 158, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Tibetan Standard, Tibetan, Central', 159, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Turkmen', 160, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Tagalog', 161, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Tswana', 162, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Tonga (Tonga Islands)', 163, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Turkish', 164, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Tsonga', 165, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Tatar', 166, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Twi', 167, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Tahitian', 168, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Uyghur, Uighur', 169, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Ukrainian', 170, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Urdu', 171, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Uzbek', 172, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Venda', 173, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Vietnamese', 174, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Volapük', 175, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Walloon', 176, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Welsh', 177, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Wolof', 178, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Western Frisian', 179, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Xhosa', 180, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Yiddish', 181, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Yoruba', 182, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Zhuang, Chuang', 183, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Zulu', 184, dsft.id, 'not_popular' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
INSERT INTO controlledvocabularyvalue (strvalue, displayorder, datasetfieldtype_id, displaygroup) (SELECT 'Not applicable', 185, dsft.id, 'not_applicable_group' FROM datasetfieldtype dsft WHERE dsft.name =  'titleTranslationLanguage');
