UPDATE datasetfieldtype SET displayorder = displayorder + 2
    WHERE displayorder > 23 AND metadatablock_id = 1;

INSERT INTO datasetfieldtype (advancedsearchfieldtype, allowcontrolledvocabulary, allowmultiples, description,
                              displayformat, displayoncreate, displayorder, facetable, fieldtype, name, required, title,
                              uri, validation, watermark, metadatablock_id, parentdatasetfieldtype_id,
                              inputrenderertype, inputrendereroptions)
VALUES (true, true, true, 'Academic disciplines relevant to the Dataset.',
        '', true, 24, false, 'TEXT', 'disciplineMEiN2022', false, 'Discipline (MEiN 2022)',
        '', '[{"name":"standard_input"}]', '', 1, NULL,
        'VOCABULARY_SELECT', '{}');

INSERT INTO datasetfieldtype (advancedsearchfieldtype, allowcontrolledvocabulary, allowmultiples, description,
                              displayformat, displayoncreate, displayorder, facetable, fieldtype, name, required, title,
                              uri, validation, watermark, metadatablock_id, parentdatasetfieldtype_id,
                              inputrenderertype, inputrendereroptions)
VALUES (true, true, true, 'Fields of research and development relevant to the Dataset.',
        '', true, 25, false, 'TEXT', 'fieldOfResearchAndDevelopment', false, 'Field of R&D (UNESCO, OECD)',
        '', '[{"name":"standard_input"}]', '', 1, NULL,
        'VOCABULARY_SELECT', '{}');

INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'archaeology', 'Humanities', 0, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'ethnology.and.cultural.anthropology', 'Humanities', 1, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'philosophy', 'Humanities', 2, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'history', 'Humanities', 3, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'linguistics', 'Humanities', 4, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'literary.studies', 'Humanities', 5, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'culture.and.religion.studies', 'Humanities', 6, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'arts.studies', 'Humanities', 7, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'polish.studies', 'Humanities', 8, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'architecture.and.urban.planning', 'Engineering.and.technology', 9, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'automation.electronics.electrical.engineering.and.space.technologies', 'Engineering.and.technology', 10, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'information.and.communication.technology', 'Engineering.and.technology', 11, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'safety.engineering', 'Engineering.and.technology', 12, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'biomedical.engineering', 'Engineering.and.technology', 13, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'chemical.engineering', 'Engineering.and.technology', 14, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'civil.engineering.geodesy.and.transport', 'Engineering.and.technology', 15, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'materials.engineering', 'Engineering.and.technology', 16, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'mechanical.engineering', 'Engineering.and.technology', 17, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'environmental.engineering.mining.and.energy', 'Engineering.and.technology', 18, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'heritage.protection.and.conservation.of.monuments', 'Engineering.and.technology', 19, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'medical.biology', 'Medical.and.health.sciences', 20, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'pharmacology.and.pharmacy', 'Medical.and.health.sciences', 21, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'medical.sciences', 'Medical.and.health.sciences', 22, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'physical.culture.science', 'Medical.and.health.sciences', 23, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'health.sciences', 'Medical.and.health.sciences', 24, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'family.studies', 'Family.studies', 25, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'forestry', 'Agricultural.sciences', 26, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'agriculture.and.horticulture', 'Agricultural.sciences', 27, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'food.and.nutrition.technology', 'Agricultural.sciences', 28, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'animal.science.and.fisheries', 'Agricultural.sciences', 29, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'economics.and.finance', 'Social.sciences', 30, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'socio-economic.geography.and.spatial.management', 'Social.sciences', 31, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'security.studies', 'Social.sciences', 32, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'social.communication.and.media.studies', 'Social.sciences', 33, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'political.and.administrative.sciences', 'Social.sciences', 34, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'management.and.quality.studies', 'Social.sciences', 35, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'law', 'Social.sciences', 36, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'sociology', 'Social.sciences', 37, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'educational.sciences', 'Social.sciences', 38, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'canon.law', 'Social.sciences', 39, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'psychology', 'Social.sciences', 40, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'international.relations', 'Social.sciences', 41, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'astronomy', 'Natural.sciences', 42, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'biotechnology', 'Natural.sciences', 43, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'computer.and.information.sciences', 'Natural.sciences', 44, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'mathematics', 'Natural.sciences', 45, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'biological.sciences', 'Natural.sciences', 46, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'chemical.sciences', 'Natural.sciences', 47, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'physical.sciences', 'Natural.sciences', 48, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'earth.and.related.environmental.sciences', 'Natural.sciences', 49, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'biblical.studies', 'Theology', 50, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'theology.discipline', 'Theology', 51, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'veterinary.science.discipline','Veterinary.science', 52, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'film.and.theatre', 'The.arts', 53, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'music', 'The.arts', 54, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT 'fine.arts.and.art.conservation', 'The.arts', 55, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'disciplineMEiN2022');

INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '1.1.mathematics', '1.Natural.sciences', 0, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '1.2.computer.and.information.sciences', '1.Natural.sciences', 1, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '1.3.physical.sciences', '1.Natural.sciences', 2, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '1.4.chemical.sciences', '1.Natural.sciences', 3, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '1.5.earth.and.related.environmental.sciences', '1.Natural.sciences', 4, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '1.6.biological.sciences', '1.Natural.sciences', 5, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '1.7.other.natural.sciences', '1.Natural.sciences', 6, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '2.1.civil.engineering', '2.Engineering.and.technology', 7, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '2.2.electrical.engineering.electronic.engineering.information.engineering', '2.Engineering.and.technology', 8, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '2.3.mechanical.engineering', '2.Engineering.and.technology', 9, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '2.4.chemical.engineering', '2.Engineering.and.technology', 10, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '2.5.materials.engineering', '2.Engineering.and.technology', 11, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '2.6.medical.engineering', '2.Engineering.and.technology', 12, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '2.7.environmental.engineering', '2.Engineering.and.technology', 13, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '2.8.environmental.biotechnology', '2.Engineering.and.technology', 14, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '2.9.industrial.biotechnology', '2.Engineering.and.technology', 15, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '2.10.nano-technology', '2.Engineering.and.technology', 16, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '2.11.other.engineering.and.technologies', '2.Engineering.and.technology', 17, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '3.1.basic.medicine', '3.Medical.and.health.sciences', 18, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '3.2.clinical.medicine', '3.Medical.and.health.sciences', 19, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '3.3.health.sciences', '3.Medical.and.health.sciences', 20, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '3.4.medical.biotechnology', '3.Medical.and.health.sciences', 21, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '3.5.other.medical.science', '3.Medical.and.health.sciences', 22, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '4.1.agriculture.forestry.and.fisheries', '4.Agricultural.and.veterinary.sciences', 23, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '4.2.animal.and.dairy.science', '4.Agricultural.and.veterinary.sciences', 24, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '4.3.veterinary.science', '4.Agricultural.and.veterinary.sciences', 25, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '4.4.agricultural.biotechnology', '4.Agricultural.and.veterinary.sciences', 26, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '4.5.other.agricultural.sciences', '4.Agricultural.and.veterinary.sciences', 27, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '5.1.psychology.and.cognitive.sciences', '5.Social.sciences', 28, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '5.2.economics.and.business', '5.Social.sciences', 29, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '5.3.education', '5.Social.sciences', 30, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '5.4.sociology', '5.Social.sciences', 31, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '5.5.law', '5.Social.sciences', 32, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '5.6.political.science', '5.Social.sciences', 33, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '5.7.social.and.economic.geography', '5.Social.sciences', 34, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '5.8.media.and.communications', '5.Social.sciences', 35, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '5.9.other.social.sciences', '5.Social.sciences', 36, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '6.1.history.and.archaeology', '6.Humanities.and.the.arts', 37, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '6.2.languages.and.literature', '6.Humanities.and.the.arts', 38, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '6.3.philosophy.ethics.and.religion', '6.Humanities.and.the.arts', 39, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '6.4.arts.arts.history.of.arts.performing.arts.music', '6.Humanities.and.the.arts', 40, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');
INSERT INTO controlledvocabularyvalue (strvalue, displaygroup, displayorder, datasetfieldtype_id) (SELECT '6.5.other.humanities', '6.Humanities.and.the.arts', 41, dsft.id FROM datasetfieldtype dsft WHERE dsft.name = 'fieldOfResearchAndDevelopment');