name: Add bugs to project board

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    name: Add bug to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/IQSS/projects/34
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: "Type: Bug"
