name: 'Generate dataverse war file'

on:
  workflow_dispatch:
    inputs:
      buildlabel:
        description: 'Custom label that will appear after the version number (the equivalent of the old "build number" entry).  Leaving it empty will default to the legacy behavior, i.e. " build <branch>-<checksum>".'
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set build number
        run: scripts/installer/custom-build-number "${{ github.event.inputs.buildlabel }}"

      - name: Build application war
        run: mvn package

      - name: Get war file name
        working-directory: target
        run: echo "war_file=$(ls *.war | head -1)">> $GITHUB_ENV

      - name: Upload war artifact
        uses: actions/upload-artifact@v7
        with:
          name: built-app
          path: ./target/${{ env.war_file }}
