name: Dataverse SPI 

on:
    push:
        branch:
            - "develop"
        paths:
            - "modules/dataverse-spi/**"
    pull_request:
        branch:
            - "develop"
        paths:
            - "modules/dataverse-spi/**"

jobs:
    snapshot:
        name: Release Snapshot
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  java-version: '11'
                  distribution: 'adopt'
                  server-id: ossrh
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
            - uses: actions/cache@v2
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2

            - name: Deploy Snapshot
              run: mvn -f modules/dataverse-spi -Dproject.version.suffix="-PR${{ github.event.number }}-SNAPSHOT" deploy
              env:
                  MAVEN_USERNAME: ${{ secrets.DATAVERSEBOT_SONATYPE_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.DATAVERSEBOT_SONATYPE_TOKEN }}

    release:
        name: Release
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'adopt'
            -   uses: actions/cache@v2
                with:
                    path: ~/.m2
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: ${{ runner.os }}-m2

            # Running setup-java again overwrites the settings.xml - IT'S MANDATORY TO DO THIS SECOND SETUP!!!
            -   name: Set up Maven Central Repository
                uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'adopt'
                    server-id: ossrh
                    server-username: MAVEN_USERNAME
                    server-password: MAVEN_PASSWORD
                    gpg-private-key: ${{ secrets.DATAVERSEBOT_GPG_KEY }}
                    gpg-passphrase: MAVEN_GPG_PASSPHRASE

            -   name: Sign + Publish Release
                run: mvn -f modules/dataverse-spi -P release deploy
                env:
                    MAVEN_USERNAME: ${{ secrets.DATAVERSEBOT_SONATYPE_USERNAME }}
                    MAVEN_PASSWORD: ${{ secrets.DATAVERSEBOT_SONATYPE_TOKEN }}
                    MAVEN_GPG_PASSPHRASE: ${{ secrets.DATAVERSEBOT_GPG_PASSWORD }}