# Solr for Dataverse
#
# See the note about Dataverse 4.2.3 vs. 4.7 at conf/docker/dataverse-glassfish/Dockerfile
#
# Note that there is a separate Dockerfile we can start with:
#
# Dataverse 4.2.3: https://github.com/pdurbin/ndslabs-dataverse/blob/v4.2.3.1/dockerfiles/solr/Dockerfile
# Dataverse 4.7: https://github.com/pdurbin/ndslabs-dataverse/blob/upgrade-4.7/dockerfiles/solr/Dockerfile
